- scss/1-settings/_colour-language.scss
- scss/1-settings/_colour-palette.scss
- styleguide/styles.scss
- styleguide/tokens.stories.js
In the design system meeting, we discussed keeping the original heritage yellow for components that are not focus. This pull request adds the brand colours to the colour language as primary (heritage blue) and secondary (heritage yellow) and adds a yellow to the palette for focus colours.
Also updated the display of the colour language and palette pages on storybook as the larger blue circles were getting difficult with so many options.
> Update colour language

- CHANGELOG.md
- haml/_navigation.html.haml
- js/navigation.js
- package.json
- scss/6-components/_navigation.scss
- styleguide/component-wrapper.js
- styleguide/components.stories.js
- styleguide/haml.stories.js
- yarn.lock
Stand alone JS/CSS version of greedy nav. 
This version does not use React - thinking behind this is that navigation should be available as soon as possible and load as few resources as possible.
Not yet tested with rails so may require some revision to integrate smoothly.
Design: https://www.figma.com/file/IZY9uqY9RPjhIUv8ol1qjf/DS_Work-In-Progress?node-id=159%3A474
Ticket: https://citizensadvice.atlassian.net/browse/NP-11
Preview:
> NP-11 greedy navigation

- CHANGELOG.md
- package-lock.json
- package.json
Fixes:
NP-200: Greedy nav behaviour breaking on Safari when user restore the screen
NP-205: Greedy navigation needs to close after the last item o menu loses the focus
> NP-200, NP-205 fix: update priority-nav fixing tabbing and resize bugs

- CHANGELOG.md
- package-lock.json
- package.json
Fixes tabbing behaviour in IE-11. As usual the code update happened in @baseonmars/priority-nav. The fix here was to use `focusout` events with IE11 instead of `blur` as IE 11 only correctly populates the `relatedTarget` event property when using `focusout`.
> NP-217 fix: update priority-nav to 1.3.1 to fix IE 11 Greedy Nav tabbing

- CHANGELOG.md
- scss/1-settings/_colour-language.scss
- scss/4-elements/_buttons.scss
The mid grey box-shadow looked a bit fuzzy once we saw it in code. 
Sonia and Shakira worked on some small design updates which keeps the box-shadow for affordance. 
There are changes to hover and focus styles as well.
> Updating button styles

- CHANGELOG.md
- js/navigation.js
- package-lock.json
- package.json
- scss/6-components/_navigation.scss
- styleguide/component.stories.js
Updates the priority nav package to 1.4.0 which brings in VoiceOver improvements.
The approach taken is slightly different from the one outlined in the ticket - this is due to a previous feature request from @shakiradamji to display the menu as the users tabs through the menu options without the need to activate the sub menu.
> NP-229: navigation VoiceOver improvements

- CHANGELOG.md
- haml/_navigation.html.haml
When I click on Benefits on the navigation bar It redirects to https://www.citizensadvice.org.uk/benefits/
> NP-214: feat: change Benefits link to point to live website

- Jenkinsfile
- bin/docker/lint
- bin/docker/network
- bin/docker/start_debug
- bin/docker/test
- bin/jenkins/fix_visual_test_report
- bin/test
- docker-compose.yml
- scripts/vr-test.js
- testing/backstop-ci.json
- traefik.toml
This adds backstopjs html report to jenkins builds. Viewable on jenkins against the job, for example:
https://jenkins.devops.citizensadvice.org.uk/job/design-system/view/change-requests/job/PR-86/BackstopJS_20Report/
> NP-272 - Running BackstopJS on Jenkins

- CHANGELOG.md
- haml/_contact_details.html.haml
Replaced H4 with P tag and appropriate styling from Contact Details as H4 tags should not be used.
> NP-325 Remove H4 from contact details

- CHANGELOG.md
- js/targeted-content.js
- styleguide/component.stories.js
Use a normal for loop vs forEach to avoid need for polyfill. The consumer should in theory transpile it but this may not happen given that the package is in node_modules.
> NP-352 Targeted content integration

- CHANGELOG.md
- haml/_breadcrumb.html.haml
- styleguide/haml_locals.rb
Renamed the breadcrumb title prop from `label` to `title` to match the API.
> NP-394 breadcrumb title field rename

- CHANGELOG.md
- haml/_advice_feedback.html.haml
- haml/_breadcrumb.html.haml
- haml/_callout.html.haml
- haml/_contact_details.html.haml
- haml/_input.html.haml
- haml/_notice_banner.html.haml
- haml/_radio_group.html.haml
- haml/_radio_group_small.html.haml
- haml/_targeted-content.html.haml
- haml/_textarea.html.haml
- styleguide/haml_locals.rb
Replace symbol hash access syntax for string, ie
`input[:error_message]` becomes `input['error_message']` in the haml templates and the data objects change from 
```
input: {
name: 'inputABC',
label: 'This is the label for the input',
hint: 'This is the hint for the input',
error_message: 'This is an error messsage',
has_error: true,
optional: true
}
```
to
```
'input' => {
'name' => 'inputABC',
'label' => 'This is the label for the input',
'hint' => 'This is the hint for the input',
'error_message' => 'This is an error messsage',
'has_error' => 'true',
'optional' => 'true'
},
```
To test the components in storybook should all look ok and work ok.
> NP-401 haml hash

- Jenkinsfile
Fixes :
```Scripts not permitted to use method groovy.lang.GroovyObject getProperty java.lang.String (org.codehaus.groovy.runtime.GStringImpl.stripMargin). Administrators can decide whether to approve or reject this signature.```
> fix: use string concatination instead of stripMargin [NP-396]

- CHANGELOG.md
- haml/_footer_feedback.html.haml
The footer_feedback component is redundant, the feedback link is now part of the footer.
> NP-415 Remove footer_feedback component

- .babelrc
- .eslintrc
- CHANGELOG.md
- package-lock.json
- package.json
- scss/1-settings/_grid.scss
- scss/6-components/_navigation.scss
- src/ts/greedy-nav/GreedyNav.spec.ts
- src/ts/greedy-nav/GreedyNav.ts
- src/ts/greedy-nav/__fixtures__/menu.html
Fixes keyboard navigation in ie11 by correctly checking document.activeElement.
I've also made some small refactors to name variables more clearly and use TS null checking features.
Finally a thicker default border is added to site nav items to prevent it 'jumping' when navigating.
JSDOM tests added, mostly as an example of how to write them - I had to make one fairly major change to allow this to work correctly which involves passing in a reference to document to GreedyNavMenu.
> feat: fix keyboard navigation in IE 11 [NP-465]

- CHANGELOG.md
- haml/_header.html.haml
- styleguide/haml_locals.rb
- styleguide/samples/_advice_collection.html.haml
- styleguide/samples/_advice_collection_adviser.html.haml
- styleguide/samples/_tables.html.haml
Introduce `alt_language` local to the `header` haml component. This will allow the public website to inject a url and title to the header which is displayed in the top right corner near the sign-in button.
Related to ticket NP-715: Fetch welsh language content.
> feature: header accepts alternative language link and title [NP-642]

- testing/features/asset_hyperlink.feature
- testing/features/step_definitions/asset_hyperlink_steps.rb
- testing/features/support/core_ext/object.rb
- testing/features/support/env.rb
- testing/features/support/helpers/regex.rb
- testing/features/support/pages/asset_hyperlink.rb
Here is the specification for Asset Hyperlink
As this is a static test. Primarily we just validate what it looks like. Given that different browsers and users will control what happens on link click, it doesn't make sense to test this.
FYI: I wasn't sure if the `F` which comes out of the content for the icon meant anything, so I just validate that there is "some" icon value, not specifically an F.
> feature: Specification: Asset Hyperlink [NP-716]

- .editorconfig
- Jenkinsfile
- testing/cucumber.yml
Browserstack is now enabled for the design-system
It will only run on master, and will run to begin with 3 combinations of Chrome (Win10,Win7,OSX Mojave).
Once we've had this running for a **couple of weeks** we can do the following...
- Refactor runners to include more browser combinations
- Alter / add extra info dumps to slack
- Monitor timings to ensure we're not going too crazy (As we're still adding more tests)
Once we've had this running for a **few months** we can do the following...
- Start having artifacts publish automatically to slack
- Look into whether we should move the tests elsewhere
- Look into running browserstack directly on branches (Obviously a smaller subset of browsers)
- Research into getting it running on a timer
> feature: Enable Browserstack [NP-765]

- Jenkinsfile
- docker-compose.yml
- testing/features/support/core_ext/capybara/selenium/driver/firefox_driver.rb
Since merging the PR for 765 (Introduce and use Browserstack, a couple of small issues have become more apparent. This PR fixes them.
- `Jenkinsfile`
- Our archiving wasn't working properly because our code sits inside `testing`
- The newly mounted dir should now be archived correctly
- `docker-compose.yml`
- This wasn't passing downstream variables
- The build was always using default driver config (Kind of making browserstack redundant).
- `capybara`
- Has a bug where the patching for their endpoints for Firefox uses a private method. In Chrome they make the private method public, but don't do this for Firefox. I've patched this and raised an issue (Linked in patch).
> bugfix: Browserstack CI fixes [NP-765]

- testing/features/advice_feedback.feature
- testing/features/asset_hyperlink.feature
- testing/features/buttons.feature
- testing/features/callout.feature
- testing/features/contact_details.feature
- testing/features/step_definitions/advice_feedback_steps.rb
- testing/features/step_definitions/contact_details_steps.rb
- testing/features/support/pages/advice_feedback.rb
- testing/features/support/pages/asset_hyperlink.rb
- testing/features/support/pages/buttons.rb
- testing/features/support/pages/callout.rb
- testing/features/support/pages/contact_details.rb
This is a really small spec as it's static and almost completely configurable.
Only assertions from story / Panos' input was that the top item should be bold and there should be at least 1 paragraph at all times.
> feature: Specification - Contact Details [NP-717]

- Jenkinsfile
IE11 has regressed on window resizing
MAC Chrome looks flaky and is not performing some commands as expected.
Will remove triage and re-add extra tickets down the line
> hotfix: Remove some drivers whilst we investigate issues

- CHANGELOG.md
- haml/_error_summary.html.haml
- scss/6-components/_error-summary.scss
- styleguide/component.stories.js
Reasons for change:
Error summary must be focusable and have correctly styled links with focus.  This PR address those two issues.
Changes:
- correct focus styles on error summary and links within
- add accessibility attrs and links into haml template
- documentation updates to cover how the error summary should behave
> bugfix: add focus styles to error summary [NP-856]

- testing/features/buttons.feature
- testing/features/step_definitions/advice_feedback_steps.rb
- testing/features/step_definitions/buttons_steps.rb
- testing/features/support/drivers/local.rb
As discussed in new_platform_builds, some tests were falling during the builds in Jenkins.
Example: https://jenkins.devops.citizensadvice.org.uk/job/design-system/job/master/150/console
This PR fixes the in the problem in some steps of buttons_steps and advice_feedback steps for Safari Browser.
> bugfix: Tests failing in Safari during jenkins build [NP-855]

- .stylelintrc.json
- scss/2-tools/_animation.scss
Stylelint have sensibly deprecated `blacklist` properties in favour of `disallowed-list` versions. Updating the config and comments to cover this.
> Stylelint blacklist → disallowed-list

- testing/features/buttons.feature
Because of a breaking change to the button styles the current master build fails as browserstack tests run against the current github-pages URL which is not reflective of what's in master.
For now I'm using the `@future_release` tag to mark those tests as pending release. Longer term it would be great to get the release process to a point where browserstack tests can be run against the same thing as the build.
Having to go by the test failures on this as I can't confirm this 100% works until it is run on master (unless I'm missing something!)
> Tag button features with future release

- testing/features/buttons.feature
As discussed with @luke-hill in https://github.com/citizensadvice/design-system/pull/235 all button features tagged with `@future_release`.
> All button tests tagged with @future_release

- scripts/release.js
Noticed that the release script formats the `package.json` file with **4** spaces where `package.json` convention, and our `.editorconfig` settings for the project as a whole specify **2**. This causes some awkward diffs and conflicts when performing a release.
Wondering if longer term we could either defer to `npm version`, use something like https://github.com/sindresorhus/np to avoid the need to roll our own version bumping script? Or alternatively use `prettier` as a formatter when updating the file?
The simplest change I could make for now is to bring the number of spaces in sync with the config.
> Match release formatting with editorconfig

- testing/features/breadcrumbs.feature
- testing/features/step_definitions/breadcrumbs_steps.rb
- testing/features/support/pages/breadcrumbs.rb
Added Feature specification for Breadcrumbs
NB: I used the capybara helper `has_link?` for links, as the specific URL's contained aren't validatable (As they link off to invalid URLs) - These are then used as `have_link` for the assertion. But I don't provide more details, as they're irrelevant.
> feature:Breadcrumbs Spec [NP-623]

- Jenkinsfile
- docker-compose.yml
- testing/features/buttons.feature
- testing/features/step_definitions/buttons_steps.rb
- testing/features/support/drivers/browserstack/base.rb
- testing/features/support/drivers/browserstack/payload_values_generator.rb
- testing/features/support/env.rb
- testing/features/support/helpers/env_variables.rb
- Fix browserstack chunks into more granular ones.
- This is the same work that went into `public-website-cucumber` available here: https://github.com/citizensadvice/public-website-cucumber/pull/81
- PR's will be grouped into one cumulative pot (Irrespective of commits)
- `master` builds will all be grouped according to the instance of `master`
- Local builds will be grouped by month
**NB:** I also quickly re-enabled some button tests and remove some button tests FYI @davidsauntson
> feature: Browserstack Chunking [NP-854]

- testing/features/buttons.feature
- testing/features/step_definitions/buttons_steps.rb
- testing/features/support/drivers/browserstack/payload_values_generator.rb
- testing/features/support/pages/buttons.rb
In collaboration with David R we are going to do a couple of things.
- Try spec out a new fully formed ticket for testing Button states (The combination of BDD / VRT tests both don't cover the purpose and cause issues
- To remove the BDD tests from this portion of the repo **but** retain the assertion logic. So that if we cannot fix them, we can revert back to these with some more helpers (Hover over/Hover off e.t.c.)
NB: I also added `nil-safe` checks for `docker_tag`. This works on anything after ruby 2.3 (We're using 2.6), so no issues here. Was a minor bugfix/refactor.
> refactor: Flaky button tests [NP-XXX]

- testing/features/support/drivers/browserstack/payload_values_generator.rb
- testing/features/support/helpers/env_variables.rb
Fix browserstack partitioning for Design System
As this used a different syntax / naming convention for their DOCKER_TAG env vars, we need a slightly different string sanitization. We also use SHA instead of build ref as that isn't passed through to Docker for some reason. Not really important as we still have the granularity required.
> Browserstack Partioning Fix

- testing/features/support/drivers/browserstack/base.rb
Use new more stable browserstack endpoint temporarily whilst they fix other issues
cc/ @david-lake / @adriana-rus
> feature: TEMPORARY - New browserstack endpoint [NP-1048]

- CHANGELOG.md
- haml/_navigation.html.haml
- src/ts/greedy-nav/Config.ts
- src/ts/greedy-nav/__fixtures__/menu.html
The greedy nav default config used a naked `nav` element to initiate the greedy nav behaviour.  This PR changes this to a specific `.js-cads-greedy-nav` class.
> fix: add specific js-* class to greedy nav, config and tests

- Jenkinsfile
Adds a full build to run at 2AM every night to catch any regressions that have merged in during the day.
> feature: Run nightly design system regression tests [NP-292]

- package-lock.json
- package.json
- src/js/callout.js
- src/js/callout.test.js
- src/js/header.js
- src/js/header.test.js
- src/js/targeted-content.js
- src/js/targeted-content.test.js
Adds testing-library unit tests for:
- callout heading swap
- header search toggle
- targeted content
Also fixes lint warnings and general pattern of using `try/catch` and `console.logs` in favour of using guard statements. Removed lots of `[0]` code by using `querySelector` which returns the first match by design.
> Component unit tests and lint fixes

- testing/features/support/core_ext/cucumber/core/test/case.rb
- testing/features/support/helpers/page.rb
- Fix cucumber hooks by using the feature file name as opposed to feature name (No longer in pickle).
- This has been broken since the cucumber4 upgrade
NB: This is copied from the `public-website-cucumber` fix done a week or so ago.
> bugfix: Cucumber Hooks [NP-1099]

- styleguide/samples/_forms.html.haml
The code example in the new components includes 2 acutes ` 
When copying the component from storybook, they are included in the clipboard.
We should consider removing that, so bugs like this don't go by unnoticed.
This pull request just removes the acute from the forms example page.
> bugfix: Remove incorrect acutes [NP-973]

- bin/test
- package.json
- src/ts/greedy-nav/GreedyNav.test.ts
- src/ts/greedy-nav/tsconfig.common.json
- src/ts/greedy-nav/tsconfig.json
Bit of a 🐰 🕳️  this one.
Introduced a build error in https://github.com/citizensadvice/design-system/pull/360 where a) I wasn't excluding `.test.ts(x)` files correctly and b) my changes (correctly) highlighted some typescript errors in the tests.
**However**: neither of these were caught because we don't actually _build_ the lib directory at any point in CI. We technically only test that the Storybook webpack pipeline works, not that the actual distributed files are built correctly until we run a build ourselves. As a short-term fix I've included `npm run build` in the CI step, but we should probably revisit this.
> Fix npm build script

- testing/features/footer.feature
- testing/features/header.feature
- testing/features/step_definitions/footer_steps.rb
- testing/features/step_definitions/header_steps.rb
- testing/features/support/helpers/env_variables.rb
- testing/features/support/helpers/page.rb
**Previously:**
When firefox loads up a new tab. It first loads `about:blank`. Because this is a static white page. Selenium detects the page has loaded correctly and continues on.
Shortly after a "redirect" then changes the URL. And selenium then goes into "load" mode again and waits for the page to load. However by this time, it's too late, as we've checked the url and triggered a failure.
NB: This doesn't appear to affect chrome.
**Now:**
Explicitly wait until the url "isn't" `about:blank` if on firefox, and we've asked it to wait for a new url.
> bugfix: Firefox new tab issue [NP-1172]

- testing/features/footer.feature
The Footer test mentioned here fails on Firefox
I have created a breakout ticket in NP-1173 to tackle this issue with more details in it. TL;DR - On Firefox <80 this functionality isn't working as specified.
> bugfix: Mark failing test [NP-1172]

- .storybook/manager.js
- .storybook/preview.js
- package-lock.json
- package.json
- styleguide/translations/translated.stories.mdx
This features allows the design-system locale to be set via the `locale` query string parameter.
This works with both the main site and the component iframe pages.
Add `&locale=cy` to the end of a url to test. Currently the translation documentation is the only translated feature (pending updated strings).
I need to test whether the polyfill is needed, I'm fairly sure it will..
> feature: locale switch url [NP-1165]

- testing/features/footer.feature
- testing/features/step_definitions/footer_steps.rb
- testing/features/support/helpers/page.rb
So we now do a 3 step check during out wait for switch context
1) Wait until 2 windows have been detected
2) Once we have 2 windows (Note that a Tab and window are treated the same in this subsection of the Capybara API), detect which window is **not** the one we have current browsing context in (Always the other one) - Then switch to it
3) Wait until the current windows url is not `about:blank`
This should ensure we are always on the correct window, and that we have the correct loaded context.
> bugfix: Footer: Report this Page tests working! [NP-1173]

- .storybook/manager.js
- .storybook/preview.js
- .storybook/theme.js
Extracted from https://github.com/citizensadvice/design-system/pull/409
Allows the docs to use Open Sans, rather than the default storybook docs font.
> Allow docs to use brand font

- CHANGELOG.md
- scss/4-elements/_misc.scss
- scss/5-objects/_page-content.scss
- scss/5-objects/_prose.scss
- scss/5-objects/objects-imports.scss
- scss/6-components/_breadcrumbs.scss
- styleguide/sample-pages/advice-collection/_advice_collection.html.haml
- styleguide/sample-pages/advice-collection/_advice_collection_adviser.html.haml
- styleguide/sample-pages/generic/_forms.html.haml
- styleguide/sample-pages/generic/_tables.html.haml
Whilst working on box lists I ran into an issue where we need to break out of the grid (to allow a background colour to spread full-width).
Currently the `cads-main-content class` prevents this:
- It constrains the width at the page level. This doubles up what `cads-grid-container` does so is both unnecessary and limiting (literally)
- It applies arbitrary styles to images
- It sets styles on `h1`s
Based on this I've split `cads-main-content` out into two classes:
- `cads-page-title`: only concerned with setting h1 styles. It also fixes an issue with the current typography styles where h1s are typically _outside_ `cads-prose` classes (in order to keep the scope as narrow as possible) so don't have the correct sizes
- `cads-page-content`: Only concerned with setting page level margins. Can …
> Split cads-main-content into multiple classes

- scripts/release.js
We don't want to push docs to live if we are releasing an alpha build.
> build: don't build docs if newVersion contains alpha

- docker-compose.yml
- docker/Dockerfile.wcag
This was the very simple one.
- Moved wcag Dockerfile to docker folder with the others
- Removed the wait-for-it package from the Dockerfile
- Fixed up the docker-compose file to deal with other changes
> refactor: Moved wcag file and removed wait-for-it [NP-1164]

- testing/features/support/core_ext/selenium/webdriver/firefox/options.rb
Creates a patch that allows Firefox drivers to be created both locally and through grid (Browserstack appears to be unaffected).
The issue stems from the fact that the key for the browsername when created directly using `browser :firefox` appears to not be camelised, whereas the chrome one is being camelised. In Se4 this case mismatch is then bubbling up as an invalid key error.
> bugfix: Local Firefox Driver [NP-1065]

- CONTRIBUTING.md
- scripts/release.js
- testing/features/support/core_ext/selenium/webdriver/firefox/options.rb
Fixes a bugbear with the current release script:
We currently manually update the package.json version but this a) causes issues with formatting and b) always misses out the version in package-lock.json. `npm version` does this for us.
The default include making a git tag of the version too which is think is a good thing to do, but if we want to disable that for now we can add `--no-git-tag-version`.
> Use npm version for release script

- .storybook/manager-head.html
- styleguide/component.stories.js
- styleguide/documentation/changelog.stories.mdx
- styleguide/documentation/contact.stories.mdx
- styleguide/documentation/getting-started.stories.mdx
A few small docs tweaks:
- Fixes an issue where the page title was always "CA Design System" rather than including the current story title
- Inline contact details into welcome guide. It was one sentence.
- Link to releases and changelog instead of inlining into Storybook. This is a partially generated doc so the formatting is a little troublesome in storybook and better to link off to github and the release page now we have it.
> Docs tweaks

- .haml-lint.yml
- CHANGELOG.md
- haml/_callout.html.haml
- scss/6-components/_callout.scss
- styleguide/sample-pages/advice-collection/_advice_collection_adviser.html.haml
**Bugfix**: Don't render empty .cads-callout-label for standard callouts (no label)
Also enables haml-lint rubocop checks for this component and fixes any warnings. Plus removes some misleading examples of nested callouts (we have a backlog task to document nested callouts more generally)
> Callout markup bug

- CHANGELOG.md
- package-lock.json
- package.json
- stats/size.json
Alpha release including:
**Deprecations**:
* Removed standalone `logo_clickable` component. Only used within header and footer
* Removed standalone `website_feedack` component. Only ever used within footer
**Bugfixes**:
* Header: Fix spacing and grid sizing around search form (NP-1024)
* Footer: Fix spacing and responsive styling (NP-1033)
* Callout: Don't render empty `.cads-callout-label` for standard callouts (no label)
> v2.1.0 alpha.0

- Jenkinsfile
- testing/features/oisc_warnings.feature
- testing/features/support/hooks.rb
Now we have the Design-System running stably again (Admittedly with some belt-n-braces approaches). We should look to re-enable some more testing candidates and also streamline our existing ones.
This is still a work in progress and browsers/versions are very much up for discussion. But fundamentally this time we introduce iPhone's into our testing matrix.
The code for enabling these was done last Sprint, but I've only just wanted to introduce them now after running them privately for a little while. You'll note the format of BROWSERSTACK_CONFIG_OPTIONS is slightly different. Although this is not mandatory (Essentially the 3rd parameter on iPhone's is always the same as the 2nd, and as such it can be omitted - i.e. `iPhone8_12_12 == iPhone8_12`)
> feature: Automation Candidate Triage [NP-991]

- testing/features/step_definitions/oisc_warnings_steps.rb
Safari has less unusable space so it appears at a relative lower space
Safari windows have different "usable" spaces. So we need to account for that in our sticky test.
> Hotfix: Safari CI test

- testing/features/oisc_warnings.feature
- testing/features/support/drivers/browserstack/ios.rb
- testing/features/support/helpers/env_variables.rb
- testing/features/support/hooks.rb
These two tests appear to fail on iOS12. So we've broken them out and conditionally skipped them only on iOS12
> Skip scenario on iOS12 device

- haml/_input.html.haml
Using the input component in a rails form and realising the input values are not submitting with the form because the `name` attribute is not set.
This PR set the attribute `name: input['name']` on the Input component.
This change does not change the UI or the way it functions.
> [bugfix] Updating input component to include name attribute [SMP-101]

- package-lock.json
- package.json
It looks like this update was excluded from dependabot at some point as we are a couple versions behind, but this is safe to upgrade. Tested and the output is the same between versions.
> Upgrade postcss-url to v10.1.0

- haml/_footer.html.haml
- scss/1-settings/_colour-language.scss
- scss/6-components/_footer.scss
This PR adds variables to the footer to allow it to be styled correctly for AdviserNet.
**The logo is wrong in this screenshot, but here's an example of what's possible**
> feat: add variables to allow footer to be styled [NP-662]

- scss/1-settings/_colour-language.scss
- scss/6-components/_footer.scss
Needed to add these variables to fully allow for advisernet footer styling
**(don't mention the logo!)**
> fix: footer variables to allow for full styling

- CHANGELOG.md
- package-lock.json
- package.json
- stats/size.json
```
lib.css decreased by 20%/14997b (58327 vs 73324)
These files have changed size over 10%:
```
(for once!)
This is just a patch release on previous alphas to add more styling variables to header, footer and search button.
> Release/v2.1.0 alpha.2

- Rakefile
- testing/features/oisc_warnings.feature
- testing/features/support/drivers/browserstack/ios.rb
- testing/features/support/helpers/env_variables.rb
- testing/features/support/hooks.rb
TL;DR - Fixed the issue by not testing the scenarios on iOS11/12
Essentially the code will never work on iOS11/12 because each of those devices / OS' has differing behaviour for the scrollbar appearing "sticky" and the close button appearing.
`safaridriver` version 13 does start to mitigate this issue, and all tested devices on iOS13 seem fine (For scrolling and showing the close button). I suggest given we have a working staple, we just wait until we stop supporting iOS11/12
> bugfix: Sticky issues (Omit testing on all problematic versions) [NP-1297]

- testing/features/page_review.feature
- testing/features/step_definitions/page_review_steps.rb
- testing/features/support/components/asset_hyperlink.rb
- testing/features/support/components/base.rb
- testing/features/support/components/contact_details.rb
- testing/features/support/components/footer.rb
- testing/features/support/components/page_review/standard.rb
This is a new spec, but a really simple one - As the component is just plain text.
As part of this I refactored all "old" style components to validate the initial form, but the base validation is just the root element is present (And again this is overloaded with most new components).
I did this, as for Page Review there is literally nothing we can wait on we don't already validate on. Because it's such a threadbare component.
NB: I didn't validate date format, as I wasn't sure if we wanted to do this. cc/ @sheldonsmiltnieks Maybe one for you to rule on?
> feature: Page Review Spec [NP-1183]

- CHANGELOG.md
- src/js/header.js
- src/js/header.test.js
Spotted in https://github.com/citizensadvice/public-website/pull/531
Correctly guard for when header is not present.
> Correctly guard for when header is not present

- CHANGELOG.md
- haml/_footer.html.haml
- locales/cy.yml
- locales/en.yml
- scss/4-elements/_links.scss
- scss/6-components/_footer.scss
This PR is connected to the footer work. The link pseudo selectors need to be defined in this order to correctly style visited links which are focused.
Whilst here also wrapped the footer in a nav element. I'm waiting on translations.
> fix: link pseudo selector ordering and wrap footer in nav element [NP-662]

- testing/.env.example
- testing/features/header.feature
- testing/features/step_definitions/header_steps.rb
After all refactor work the header tests are now stable and can be re-enabled.
I've tacked on a slight bug-fix to the `env.example` file to enable local running. Users should set the new variable to `artifacts` locally.
> feature: Re-validate and re-enable Header tests [NP-761]

- CHANGELOG.md
- haml/_footer.html.haml
- haml/_header.html.haml
- styleguide/components/footer/footer.stories.mdx
- styleguide/components/header/header.stories.mdx
- styleguide/haml_locals.rb
This PR updates the header and footer to accept a "homepage_url" which
allows the consuming code to configure it appropriately.
> feat: Set logo links in header and footer via template local [NP-1274]

- CHANGELOG.md
- package-lock.json
- package.json
- stats/size.json
- Targeted content: Now uses accesible disclosure pattern instead of `details` and `summary`
> v3.2.0 alpha.1

- haml/_header.html.haml
- locales/cy.yml
- locales/en.yml
- testing/features/header.feature
- testing/features/step_definitions/common_steps.rb
- testing/features/support/components/header/standard.rb
- testing/features/support/helpers/javascript.rb
- testing/features/support/helpers/page.rb
- testing/features/support/parameter_types.rb
I have added spec validation for skip-links. However as this wasn't something directly I fleshed out. I'm not 100% sure I've covered it well. (Hence tagging sheldon as well to look at Business cases).
There's a tiny bit of tech-debt in this PR - Which will be fixed soon (It's in capybara master, but not a versioned candidate). It's something a lot of people have got fixed up in Capybara and it will filter to selenium (When you tell a page to do something native, do it, don't complain).
NB: I've altered a tiny bit of haml/labels. Let me know if this is ok!
> feature: Spec: Skip links (Header only) [NP-1181]

- Jenkinsfile
- Rakefile
- testing/cucumber.yml
The change from grid to other was late in the previous PR, and the update to the Jenkinsfile was missed.
- Updated artifact search path to use the correct other path when running grid tests
> bugfix: Corrected path for grid test artifacts [NP-1273]

- locales/cy.yml
This is used to aria-label the footer navigation.
> feat: translated aria label for footer navigation

- CHANGELOG.md
- scss/4-elements/_buttons.scss
Limit transition to just the `background` property to avoid unwanted transition animations. Probably hard to see in GIF form but:
**Before:**
**After:**
https://citizensadvice.atlassian.net/browse/NP-1372
> Fix button animation

- testing/features/footer.feature
- testing/features/step_definitions/footer_steps.rb
- testing/features/support/components/footer/default.rb
- testing/features/support/components/footer/minimal.rb
Migrate the existing Footer scenario into a new variant scenario.
- create a folder footer in support/components;
- separate each type of footer in a different file, default.rb and minimal.rb;
- change elements and sections to its respective support file;
- create a new scenario for minimal footer
- adjust some step_definitions
> Feature: /np 1263 ds footer migration

- testing/features/footer.feature
This PR just add the tag @not_mobile in the Scenario: Users can report a problem about the specific page they are on.
A permanent fix is going to be done soon, but in order to not block any developers builds this is the fastest solution for now.
> Add the tag not_mobile for Scenario

- .storybook/main.js
Scope `stories` glob to be the `styleguide` directory rather than searching the whole project. 
Not hugely noticeable on master but makes a big difference in the context of https://github.com/citizensadvice/design-system/pull/594 where there are far more files.
> Scope stories glob

- scss/6-components/_navigation.scss
Fix to 4.0.0-alpha.1 to make visited links in the global navigation white.
> fix: make nav visited links white

- testing/features/contact_details.feature
The docs will need to be updated for this test to work with the current setup. This tag can be removed in 4.0.0+
> test: disable contact details tests pending docs update

- Jenkinsfile
Ugly fix to handle the container naming issue. When design-system builds container images on the master branch, it uses a image tag like dev_ruby_master. This tag doesn't exist in the repository, so should be rebuilt using the caching of the primary image (e.g. ruby). Because it wasn't getting removed, when a big change happened, each of the parallel tests had a chance of picking up the pre-change image from the last run - or rebuilding the post change image.
This adds some steps to ensure that after every run of the tests, these local container tags get removed. The layers and their hashes still exist, so the benefits of caching are still there, they just won't be used if they are supposed to have changed.
> hotfix: Fix image caching on master branch

- CHANGELOG.md
- haml/_footer.html.haml
Add js-cads-footer-feedback class to the footer feedback link so that it can be selected without relying on classes used for styling.
This will be used in public-website to augment the link with the browsers userAgent.
> feat: add js class to footer feedback link [NP-1463]

- testing/features/header.feature
- testing/features/support/components/header/standard.rb
This is now fixed same as in public-website
We use option+tab to skip through them on safari. They are still not enabled for mobile as this concept is irrelevant there
> bugfix: Skip Links [NP-1396]

- testing/features/breadcrumbs.feature
- testing/features/step_definitions/breadcrumbs_steps.rb
- testing/features/support/components/breadcrumbs/sitewide.rb
- testing/features/support/hooks.rb
Some breadcrumbs scenarios were falling on the iPhone because breadcrumb behaves differently on responsive screens.
This PR fixes those problems by expecting different results for mobile_phones.
> bugfix: Fix Breadcrumb tests for iPhone [NP=1253]

- .prettierignore
- .rubocop.yml
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- Rakefile
- i18n-tasks.yml
- locales/cy.yml
- locales/en.yml
Re-do of https://github.com/citizensadvice/design-system/pull/665 but using [i18n-tasks](https://github.com/glebm/i18n-tasks)
- Adds rubocop-rake
- Add and configure i18n-tasks
- Runs `i18n-tasks normalise` to sort keys, excludes from prettier check as this formatting conflicts
- Adds missing keys to `targeted_content`, fixing content errors
- Removes unused keys flagged by `i18n-tasks unused`
- Runs `i18n-tasks health` in CI to guard against future issues
> Locale lint using i18n-tasks

- CHANGELOG.md
- scss/6-components/_pagination.scss
https://citizensadvice.atlassian.net/browse/NP-1490
> Missing focus state on active page on pagination when tabbing.
Turns out this was exactly what it sounds like. Active pages were missing a link focus state.
> fix: apply focus state to active pagination page

- scss/6-components/_header.scss
Shows search input and links in the header when javascript is not loaded.
Updated margins as per @minniessuyuhuang request, reduced specificity of header classes to remove conflict with no-js class
> feat: show links and search in absence of js

- testing/visual-regression/backstop-common.js
I'm not having any luck replicating the vrt failures locally, despite trying:
- npm clean install of main and vrt package.jsons
- deleting docker containers and rebuilding from images locally and running the vrts with those
- reverting the first PR merge after the last green build overnight
- deleting all the reference images and rerunning the tests in CI with those
Not really sure why they are failing - perhaps a different version of puppeteer in being used in CI?  But npm ci would have flagged that I think.
Anyway, upping the threshold on the failing tests which relate to the svg in the header and footer.  Any other ideas welcome.
> test: increase thresholds for footer and header

- Rakefile
Small build improvement I spotted whilst doing this experiment: https://github.com/citizensadvice/design-system/pull/757
Remove `build` dependency from `npm:lint` and `npm:jest` step. It shouldn't be needed and results in us doing unnecessary builds.
> No need to run build as a prerequisite  to eslint or jest tasks

- haml/_header.html.haml
- scss/4-elements/_links.scss
- scss/6-components/_navigation_greedy-nav.scss
- styleguide/components/buttons/buttons.stories.mdx
- styleguide/components/header/header.stories.mdx
- styleguide/haml_locals.rb
Adds support for rendering the sign out link as a form.
* Add a `cads-linkbutton__regular` class as link buttons are usually bold
* Add `form` boolean parameter to header links
* Add styles for mobile dropdown
* Fix styling so header links displayed in dropdown stretch full length of the dropdown (previously had 1rem left padding which differs from other navigation links)
* Update docs to include link button styling.
should look the same as before
Mobile dropdown styling
> feat: header sign out link can be a form [NP-1604]

- Jenkinsfile
Temporary measure for 3-4 weeks whilst we ...
- Sign our new BS contract
- Migrate all users over to new "potting" system
- Work out how to get manual runs working again
- Fix up VAULT access for Dual Access API keys
Then we can re-enable the testing on iPhones
> feature: Disable Mobile testing for Design-System [NP-1591]

- CHANGELOG.md
- src/ts/greedy-nav/GreedyNav.test.ts
- src/ts/greedy-nav/GreedyNav.ts
- src/ts/greedy-nav/__fixtures__/menu.html
Restores the close on blur functionality for the last item in the greedy nav dropdown. 
- updates header link copying to include a `js-cads` class later used to identify the last item in the copied header links (handles both `a` and `button` elements for Sign out
- calculates the last item in the dropdown based on whether the copied links are visible or not 
- update test fixtures to include the copied links
> Fix: close menu on last item blur [NP-1624]

- bin/docker/visual_regression
- docker/Dockerfile.ca-styleguide
`backstopjs` is part of a sub project, so we need to read the version number from the correct package.json.
> test: read backstopjs version from visual-regression folder

- haml/_targeted_content.html.haml
Some of the cucumber tests (https://github.com/citizensadvice/public-website/pull/850) will rely on `h2` as a selector for the targeted content title.
This PR adds a `data-testid` attribute to the title element so the selector can be updated when the design-system is next updated in the public-website repo.
> feat: add test id to targeted content headings

- testing/features/step_definitions/targeted_content_steps.rb
- testing/features/targeted_content.feature
https://citizensadvice.atlassian.net/browse/NP-1560
Failing scenarios were due to a `ends_with` check which needed to be `starts_with`
> Enabled targeted content tests [NP-1560]

- src/js/targeted-content.js
- styleguide/components/targeted-content/_anchor.html.haml
Targeted contents do not alter the window's scroll position, which means when you close a long targeted content via the 'Close' button at the bottom, lots of content is skipped.  The epi site scrolls the user to the top of the targeted content on close, this PR replicates that behaviour.
> Fix: NP-1699 scroll to top of targeted content on close

- Jenkinsfile
Reverts citizensadvice/design-system#771
This should be merged at the start of Sprint 25 (After firebreak), as all of the requisite work will have been completed by then.
> Revert "feature: Disable Mobile testing for Design-System [NP-1591]"

- src/js/targeted-content.js
- styleguide/documentation/getting-started.stories.mdx
Fixes issue where scrolling viewport to align with top of targeted content on close resulted in an undismissed OISC warning covering the targeted content.
Just using `scrollIntoView` instead for simplicity and robustness (can't really be sure what other consumers of the design system will be rendering at the top of the viewport).
> fix: scroll targeted content to center of viewport

- testing/features/navigation.feature
Removes tests that require tabbing into dropdown from mobiles (users would use accessibility / gesture control to achieve this).
> fix: dont run tabbing tests on mobile

- testing/features/navigation.feature
Marks some more tests to be skipped on mobiles whilst the issues are triaged (tickets raised).
> Fix: mark some mobile tests as failures for greedy nav

- testing/features/support/components/header/standard.rb
- testing/features/support/components/navigation/standard.rb
- testing/features/support/helpers/page.rb
Refactors a method inside the header support file into a helper file, to allow a common way of sending tabs that caters for safari weirdness.  Will unblock one of the failing feature tests for navigation.
> Fix: tab helper NP-1765

- scss/1-settings/_colour-language.scss
- scss/2-tools/_interactive-elements.scss
- styleguide/foundations/_colour-export.scss
Decouples the nav item hover color from the text color of a normal link when hovered over.  This allows correct theming of the nav in advisernet.
Removes the advisernet link hover color from the design-system which wasn't used by anything anyway.
> fix: fix nav hover background color NP-1875

- CHANGELOG.md
- haml/_targeted_content.html.haml
- src/js/targeted-content.js
- styleguide/components/targeted-content/targeted-content-docs.mdx
This is coded in the positive, with a default set to true so existing behaviour is maintained.
Set local `"targeted_content" => { "close_button" => false }` to omit the close button. This is useful when targeted content is as part of a UI that does not require the close button - specifically this applies to the Expandable Sidebar that is part of the public advice website.
> feat: option to remove the close button for targeted content [NP-757]

- CHANGELOG.md
- haml/_header.html.haml
- locales/cy.yml
- locales/en.yml
- src/js/header.js
- src/js/header.test.js
- testing/features/header.feature
- testing/features/step_definitions/common_steps.rb
Fixes a bug in the mobile header where the title of the search expand / collapse button was not translated in the javascript by:
- creating translations for open and close states
- storing these in `data-` attributes on the button
- updating the js to use these attributes when updating the button title
Waiting for the Welsh translation of 'close search' but ready for review.
> WIP Fix/header button translation [NP-1884]

- CHANGELOG.md
- scss/6-components/_navigation_greedy-nav.scss
- src/ts/greedy-nav/Config.ts
- src/ts/greedy-nav/GreedyNav.test.ts
- src/ts/greedy-nav/GreedyNav.ts
- src/ts/greedy-nav/__mocks__/ResizeObserver.ts
- styleguide/documentation/getting-started.stories.mdx
Adjust the offset (I'm not sure if it's correct but this is what's needed for chrome to stop screwing up).
The CSS change is required to prevent the dropdown toggle from hanging over the edge of the page. Changes to GreedyNav are mostly house keeping - I believe further changes are in the works so did not go crazy here.
Documentation for polyfill added as well as a Mock for unit tests.
> fix: chrome resizing bug by increasing offset [NP-1603]

- package.json
We don't use a top-level .env file for anything and this was never called.
> Uninstall dotenv node module

- .github/dependabot.yml
- Makes npm schedule weekly to match with ruby dependencies
- Fixes an issue with the testing rule, package.json is at root of testing/ directory, not testing/visual-regression
> Adjust dependabot rules

- testing/features/footer.feature
- testing/features/step_definitions/footer_steps.rb
- testing/features/support/helpers/page.rb
We had a test for the footer link which opens up a new tab and switches to it.
It'd be nice to avoid needing to test cross domain. As it happens the test doesn't tell us much as this component is designed to accept any link, not specifically the one being tested.
Deleting this scenario also lets us remove some complex helper methods.
> Remove cross-domain test from the footer

- CHANGELOG.md
- haml/_callout.html.haml
- styleguide/components/callouts/_adviser.html.haml
- styleguide/components/callouts/callouts-docs.mdx
Renders callout as `section` elements as recommended by DAC.
If a `title` attribute is provided, it is rendered as an `aria-label` attribute on the `section` element.  Note that:
- this is already present in the `notice` hash created by the public website renderer
- only Adviser callouts have a meaningful title so we will need to be careful when we merge this into public website, as some non-adviser callouts will generate `notice["title"]` like `example-callout-milli-9e8r93`
> fix: callouts as sections [NP-2017]

- testing/features/header.feature
- testing/features/navigation.feature
- testing/features/notice_banner.feature
- testing/features/pagination.feature
- testing/features/search.feature
- testing/features/step_definitions/common_steps.rb
- testing/features/step_definitions/pagination.rb
- testing/features/support/components/header/standard.rb
- testing/features/targeted_content.feature
When we first enabled tablet we only enabled about 25% of tests.
This PR enables a further 50-60% the remainder all are not valid for tablet.
> refactor: Re-enable all valid tablet tests [NP-1972]

- .storybook/polyfill.js
- package-lock.json
- package.json
In https://github.com/citizensadvice/design-system/pull/1001, we introduced polyfill for storybook to allow older safari and IE browserstack tests to pass.
This has now introduced a typescript conflict between `resize-observer-polyfill` and `typescript` which is preventing build.
Testing removing the polyfill completely - this may cause the browserstack tests to fail.
> chore: remove resize polyfill from storybook

- engine/app/components/citizens_advice_components/asset_hyperlink_component.rb
- engine/app/components/citizens_advice_components/base_component.rb
- engine/app/components/citizens_advice_components/callout_component.html.haml
- engine/app/components/citizens_advice_components/callout_component.rb
- engine/app/components/citizens_advice_components/pagination_component.rb
- engine/app/lib/citizens_advice_components/fetch_or_fallback_helper.rb
- engine/config/locales/cy.yml
- engine/config/locales/en.yml
- engine/previews/citizens_advice_components/callout_component_preview.rb
- engine/previews/citizens_advice_components/callout_component_preview/adviser.html.haml
- engine/previews/citizens_advice_components/callout_component_preview/example.html.haml
- engine/previews/citizens_advice_components/callout_component_preview/important.html.haml
- engine/previews/citizens_advice_components/callout_component_preview/nested.html.haml
- engine/previews/citizens_advice_components/callout_component_preview/standard.html.haml
- engine/spec/components/base_component_spec.rb
- engine/spec/components/callout_component_spec.rb
- engine/spec/components/pagination_component_spec.rb
- styleguide/examples/callout/adviser.html
- styleguide/examples/callout/example.html
- styleguide/examples/callout/important.html
- styleguide/examples/callout/nested.html
- styleguide/examples/callout/standard.html
As we are updating the callout component in https://github.com/citizensadvice/design-system/pull/1104 I thought it worth having a quick stab at converting this to a view component. Considering this experimental as it's probably one case where we want to thrash out the API for this component a bit more.
- Add component definition and template, use block for content
- Add rspec scenarios; include new title and render check.
- Generate example files
- How do we want to validate the allowed types? We can use active model validations, but these can cause runtime errors. Maybe something like https://github.com/primer/view_components/blob/main/app/lib/primer/fetch_or_fallback_helper.rb to provide a default value if an invalid type is passed
- Should `cads-badge` be its own component? Technically …
> [Experimental] Convert callout to view component

- CHANGELOG.md
- src/js/targeted-content.js
The HTML spec states that IDs can consist of any character https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute. However, `querySelector` requires selectors that start with numbers to be escaped.
Previously, if you tried to anchor to an ID starting with a number, e.g. for paragraph numbers this would throw an error.
For our use case we can normalise the hash and use `getElementById` instead.
Also wrapping the hash behaviour in a try/catch as this is an enhancement and it's fine to fail silently if this code fails.
Fixes NP-1951
> Targeted content: Support number anchors [NP-1951]

- scss/1-settings/_colour-language.scss
- scss/4-elements/_buttons.scss
Allow for theming of `cads-button__tertiary--dark`
Will need to change public website advisernet colour language to include:
```
$cads-language__tertiary-button-dark-hover-background-colour: $cads-palette__blue-adviser-dark;
$cads-language__tertiary-button-dark-hover-colour: $cads-language__brand-primary-contrast;
$cads-language__tertiary-button-dark-border-colour: $cads-language__brand-primary-contrast;
```
> Fix/tertiary button dark theming [NP-1999]

- .github/dependabot.yml
Turns out I used an older syntax for ignoring dependabot versions. Helpfully dependabot checks itself and flagged this in a status check.
> Fix ignore syntax

- scss/4-elements/_buttons.scss
Add specific focus styles to tertiary--dark button.
> fix: add correct focus styles to tertiary dark

- testing/features/components/navigation.feature
> Clarify storybook bug

- demo/app/views/layouts/application.html.haml
- engine/app/components/citizens_advice_components/breadcrumbs.html.haml
- engine/app/components/citizens_advice_components/breadcrumbs.rb
- engine/previews/citizens_advice_components/breadcrumbs_preview.rb
- engine/spec/components/breadcrumbs_spec.rb
- haml/_breadcrumb.html.haml
- styleguide/components/breadcrumbs/breadcrumbs.stories.mdx
Add the breadcrumbs component to the design system engine:
- new view component
- rspec
- previews
- updates `mdx` docs
- removes hard-coding and translating 'Home' link (this will be duplicated in old design system HAML in a different PR)
> Feat/breadcrumb view component DS-7

- testing/browserstack_ci.env
I forgot to amend the browserstack_ci env file also alongside the grid one.
> hotfix: Add in missing base url

- Jenkinsfile
- docker-compose.yml
So I _think_ this will fix the missing `BROWSERSTACK_BUILD_NAME` key issue
> fix: add missing env var

- testing/features/components/breadcrumbs.feature
The breadcrumb story urls have changed so those tests won't pass until the next non-alpha release.
> fix: mark breadcrumbs as future release

- testing/features/support/drivers/browserstack/ios.rb
- testing/features/support/helpers/env_variables.rb
- bugfix: Allow ios to use non aliased method name
- bugfix: Allow local browserstack runs
> bugfix: IOS browser caps and local BS runs

- styleguide/foundations/grid/_basic-grid.html.haml
- styleguide/foundations/grid/_multi-column-grid.html.haml
- styleguide/foundations/grid/_responsive-grid.html.haml
- styleguide/foundations/grid/basic-grid.html
- styleguide/foundations/grid/grid.stories.mdx
- styleguide/foundations/grid/multi-column-grid.html
- styleguide/foundations/grid/responsive-grid.html
- styleguide/foundations/typography/_ordered-list.html.haml
- styleguide/foundations/typography/_plain-list.html.haml
- styleguide/foundations/typography/_unordered-list.html.haml
- styleguide/foundations/typography/ordered-list.html
- styleguide/foundations/typography/plain-list.html
- styleguide/foundations/typography/typography.stories.mdx
- styleguide/foundations/typography/unordered-list.html
One more little PR from Friday afternoon…
There's no specific haml template or component associated with these as they are foundations so you are expected to use the classes directly.
To get us one step closer to removing the haml loader from storybook lets convert the grid and typography haml templates to plain HTML.
> Convert foundations examples to plain HTML

- testing/features/components/callouts.feature
Adjusted the example heading level for nested callouts in https://github.com/citizensadvice/design-system/pull/1255 so this feature needs to be marked as future_release.
> Mark nested callouts as future_release

- testing/features/support/drivers/browserstack/ios.rb
Required by `ca_testing` upgrade in https://github.com/citizensadvice/design-system/pull/1256
> Update iOS driver signature

- .github/workflows/ci-workflow.yml
- Rakefile
- engine/previews/citizens_advice_components/callout_preview/variable_heading_levels.html.haml
- engine/previews/citizens_advice_components/contact_details_preview/example.html.haml
Runs lint tasks as separate run steps in actions and uses the provided github formatter for rubocop to give us inline annotations.
> Rubocop actions reporter

- package-lock.json
- package.json
We were only ever running this for stylelint. And with the move to github actions which gives us much faster feedback and annotations in CI there's less value in maintaining the complexity of local pre-commit hooks.
> Remove lint-staged and husky

- demo/Gemfile.lock
- engine/Gemfile.lock
- engine/app/components/citizens_advice_components/page_review.rb
- engine/citizens_advice_components.gemspec
- engine/config/locales/cy.yml
- engine/config/locales/en.yml
- engine/lib/citizens_advice_components/engine.rb
- engine/previews/citizens_advice_components/page_review_preview.rb
- engine/spec/components/page_review_spec.rb
- styleguide/components/page-review/_example.html.haml
- styleguide/components/page-review/page-review.stories.mdx
- styleguide/examples/page_review/example.html
- testing/features/components/page_review.feature
- testing/features/components/step_definitions/page_review_steps.rb
In a bit of a flow for migrating these, so doing one more whilst I have the time. Migrates the page review component.
**TODO:**
> Page review component

- engine/app/components/citizens_advice_components/search.html.haml
- engine/app/components/citizens_advice_components/search.rb
- engine/config/locales/cy.yml
- engine/config/locales/en.yml
- engine/previews/citizens_advice_components/search_preview.rb
- engine/spec/components/search_spec.rb
- styleguide/components/search/_search-with-value.html.haml
- styleguide/components/search/_search.html.haml
- styleguide/components/search/search-docs.mdx
- styleguide/components/search/search.stories.js
- styleguide/examples/search/example.html
- styleguide/examples/search/with_value.html
- testing/features/components/header.feature
- testing/features/components/search.feature
- testing/features/components/step_definitions/common_steps.rb
Adds component version of the search field.
The main change here is to treat this like the other form inputs. Rather than including the whole form element I've limited this to the field itself.
**TODO:**
> Search component

- package-lock.json
- package.json
- src/ts/greedy-nav/GreedyNav.test.ts
Prompted by https://github.com/citizensadvice/design-system/pull/1292 which pointed out that we are using `@testing-library/react` even though we don't have any react components. Switches to the equivalent method from `@testing-library/dom`.
Closes #1292
> Remove @testing-library/react

- .storybook/preview.js
- styleguide/story-helpers.js
- testing/features/components/header.feature
- testing/features/components/step_definitions/common_steps.rb
- testing/features/components/step_definitions/page_review_steps.rb
- testing/features/support/all.rb
- testing/features/support/components/base.rb
- testing/features/support/components/header/standard.rb
- testing/features/support/components/page_review/example.rb
- testing/features/support/helpers/page.rb
- testing/features/support/hooks.rb
- testing/features/support/parameter_types.rb
**Background**
We're pretty much at the point now where all our welsh language specs are in rspec component tests. I think we should strip the remaining locale code out now to make the last stages of migration simpler.
**Changes**
- Remove any remaining welsh language scenarios from functional tests
- Remove reliance on `I18n` in functional tests
- Remove `switch_language` behaviour
- Remove language switcher from Storybook
> Remove language switcher from Storybook

- engine/app/components/citizens_advice_components/success_message.rb
- engine/previews/citizens_advice_components/success_message_preview.rb
- engine/spec/components/success_message_spec.rb
- styleguide/examples/success_message/example.html
- styleguide/forms/success-message/_example.html.haml
- styleguide/forms/success-message/success-message.stories.mdx
https://citizensadvice.atlassian.net/browse/DS-36
This is the penultimate component to be migrated before we've done all of them. Only https://github.com/citizensadvice/design-system/pull/1267 remaining.
Fairly simple component. No template needed.
**TODO:**
> Success message view component [DS-36]

- engine/app/components/citizens_advice_components/footer.html.haml
- engine/previews/citizens_advice_components/footer_preview.rb
- engine/spec/components/footer_spec.rb
- styleguide/components/footer/footer-docs.mdx
Spotted whilst demoing the new components. We use `:title` for the other components that accept lists of links, like navigation and breadcrumbs. Update the new footer component to be consistent.
> Footer: Use :title instead of :label in links

- styleguide/documentation/getting-started.stories.mdx
Updates the getting started guide to reflect that `citizens_advice_components` will soon be the recommended way of using design system components within Rails apps.
Restructures the guide to make it clear you can use the styles without using Rails.
> Update getting started guide

- CHANGELOG.md
- engine/app/components/citizens_advice_components/breadcrumbs.rb
- engine/spec/components/citizens_advice_components/breadcrumbs_spec.rb
Breadcrumbs render even if there's only one item. We should probably only render if there is more than one.
Provide a single item to the `Breadcrumbs` component, e.g. just a Home link
```rb
render CitizensAdviceComponents::Breadcrumbs.new(links: [{ title: "Home", url: "/" }])
```
We should probably only render the breadcrumb trail if there is more than one item.
It renders a single item. Because it's also the "last" item it renders without a link and on small screens is hidden apart from a border.
**Single item:**
**Missing on mobile:**
(A bit hard to tell from the screenshot but all that's left is the border)
> Breadcrumbs render check

- CHANGELOG.md
- Gemfile.lock
- engine/app/components/citizens_advice_components/footer.html.haml
- engine/app/components/citizens_advice_components/footer.rb
- engine/config/locales/cy.yml
- engine/config/locales/en.yml
- engine/spec/components/citizens_advice_components/footer_spec.rb
- engine/spec/rails_helper.rb
Support dynamic copyright year in footer component. Uses `ActiveSupport::Testing::TimeHelpers` to move to a specific year when testing.
Fixes #1405
> Support dynamic copyright year in footer component

- engine/spec/components/citizens_advice_components/asset_hyperlink_spec.rb
- engine/spec/components/citizens_advice_components/badge_spec.rb
- engine/spec/components/citizens_advice_components/contact_details_spec.rb
- engine/spec/components/citizens_advice_components/page_review_spec.rb
Update more specs to use capybara matchers. We don't have to use these for everything, it's fine to mix and match nokogiri with capybara where it makes sense. But generally speaking it's feeling more natural to write.
> Update more specs to use capybara matchers

- scss/3-generics/_fonts.scss
I accidentally removed `font-display: swap` when I updated the font srcs 😬 
https://github.com/citizensadvice/design-system/pull/1531/files#diff-d91684fda3bfd2eb2c979e255ceb1812089a7304a0ec4e352e4e3b41a3b25d24L9
> fix/add font-display option to font

- .github/workflows/ci-workflow.yml
- CHANGELOG.md
- engine/.rubocop.yml
- engine/app/components/citizens_advice_components/text_input.html.haml
- engine/app/components/citizens_advice_components/text_input.rb
- engine/app/components/citizens_advice_components/textarea.html.haml
- engine/app/components/citizens_advice_components/textarea.rb
- engine/spec/components/citizens_advice_components/checkbox_single_spec.rb
- engine/spec/components/citizens_advice_components/footer_spec.rb
- styleguide/components/footer/footer-docs.mdx
A bit of a re-do of https://github.com/citizensadvice/design-system/pull/1307 but with just the Ruby version changes.
Includes a couple of Ruby 3 syntax fixes. The `**` stuff is down to https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
> When a method call passes a Hash at the last argument, and when it passes no keywords, and when the called method accepts keywords, a warning is emitted. To continue treating the hash as keywords, add a double splat operator to avoid the warning and ensure correct behaviour in Ruby 3.
Gist seems to be—based on the context Luke gave in the original PR—that Ruby 3 requires less ambiguity.
One bit of complexity here is that branch protection required checks rely on the job name. The matrix build …
> Test against multiple ruby versions

- engine/previews/citizens_advice_components/error_summary_preview.rb
- styleguide/forms/error-summary/error-summary-docs.mdx
Using plural `c.errors` array in the docs and preview file to be consistent with the public-website markup (see [PR2155](https://github.com/citizensadvice/public-website/pull/2155))
> fix: Changed the error summary docs to be consistent with public-website

- styleguide/components/section-links/section-links.mdx
While working on moving the section links to the public-webiste, I have realised that what I have in the docs is a bit outdated (using slot for `section_title`). Amended to match the current functionality.
> fix: changed the section links docs to match the preview

- testing/features/components/footer.feature
- testing/features/components/step_definitions/footer_steps.rb
Currently the browserstack build is failing because the test code on `master` has been updated to use the current year but the tests run against https://citizensadvice.github.io/design-system/?path=/story/getting-started--page which is for `5.1.0` which has last year in the deployed examples.
Rather than fixing it here let's remove it as this logic is already covered by visual tests and rspec tests.
> Fix Browserstack tests

- contributing/release-process.md
- scripts/release.js
- scripts/releaseHelpers.js
- styleguide/documentation/getting-started.stories.mdx
Rename master branch to main in release script and docs.
Fixes #1406
> chore: rename master to main

- .github/dependabot.yml
Sass-loader is at version 12.6.0 but we want to prevent dependabot from flagging future versions as this would impact the Storybook build.
> chore: ignore dependabot updates for sass-loader

- package-lock.json
- package.json
Dependabot update for `@babel/preset-env` failed as it needed an updated version of `@babel/plugin-proposal-class-properties` (the docs:build was failing: https://github.com/citizensadvice/design-system/runs/5306194174?check_suite_focus=true) . Now that this is updated, I've manually updated `@babel/preset-env`
> chore: malually updated @babel/preset-env

- scripts/release.js
Prevents the release script from adding a tag for the release by using [`--no-git-tag-version`](https://docs.npmjs.com/cli/v8/commands/npm-version#description), as the docs say to do this manually after publishing.  
Duplicate tags are potentially causing [issues](https://github.com/citizensadvice/public-website/pull/2384) in products that have the gem as a github dependency.
> fix: release script does not create tag

- .github/workflows/ci-workflow.yml
Extracted from https://github.com/citizensadvice/design-system/pull/1841
This is to a) allow us to run the demo app job earlier as it will be doing more work b) avoid running lint checks for every single version of ruby/rails. We only care about rspec tests for different versions. We'll need to add this job to the required checks after merging this.
> Allow demo-app job to run earlier

- .github/workflows/ci-workflow.yml
- demo/.gitignore
- demo/Gemfile
- demo/Gemfile.lock
- demo/README.md
- demo/config/environments/test.rb
- demo/cypress.json
- demo/cypress/fixtures/example.json
- demo/cypress/integration/axe.spec.js
- demo/cypress/integration/disclosure.spec.js
- demo/cypress/integration/navigation.spec.js
- demo/cypress/integration/pagination.spec.js
- demo/cypress/integration/skip-links.spec.js
- demo/cypress/integration/targeted-content.spec.js
- demo/cypress/plugins/index.js
- demo/cypress/support/commands.js
- demo/cypress/support/index.js
- demo/package-lock.json
- demo/package.json
- package.json
Bit of an experiment into https://github.com/citizensadvice/design-system/issues/1398 to move more of our tests to run against the demo app using Cypress.
- Adds Cypress testing support to the demo app using https://github.com/testdouble/cypress-rails
- Adds an accessibility smoke test for every component preview using https://github.com/component-driven/cypress-axe
- Adds reference examples of component tests for: navigation, skip links, disclosure, targeted content, and pagination. Basically everything that has an interaction to it with the exception of the header which I can add if this looks good.
I've added explanatory comments to each step to call out the main changes.
From within the `demo/` directory you can run the following commands.
**Running using the cypress UI**
``` …
```
> Test basic cypress workflow

- .adr-dir
- CONTRIBUTING.md
- contributing/adr/0001-record-architecture-decisions.md
- contributing/adr/0002-run-automated-tests-against-demo-app.md
- contributing/adr/0003-use-cypress-for-automated-tests.md
- contributing/adr/README.md
- contributing/architecture.md
We have made a number of architecturally significant decisions around how and when we test our components. We should document these decisions.
Using this as an excuse to set up a basic ADR structure using adr-tools. As we manage our work through github projects storing our ADRs alongside the code makes most sense.
I've also include an architecture overview as suggested by @marianayovcheva to hopefully make it a little clearer what the boundaries are between parts of the design system.
> Add ADRs for recent testing decisions

- CHANGELOG.md
- engine/app/components/citizens_advice_components/footer.rb
Extracted from https://github.com/citizensadvice/design-system/pull/1874
Use simpler `Time.current.year` rather than `Time.zone.today.year` for footer year. Allows component to be more portable and usable outside of a Rails context.
> Footer: Simplify how year is calculated

- CHANGELOG.md
- scss/5-objects/_prose.scss
Applies @marianayovcheva's fix for external links when used outside of the production domain.
Fixes https://github.com/citizensadvice/design-system/issues/1761
Feeling like we should definitely open up the conversation about removing these icons in the long term but let's at least get them working reliably again after my previous half-fix 🙈
> Fix external link styles

- demo/Gemfile
- demo/Gemfile.lock
- design-system-docs/Gemfile
- design-system-docs/Gemfile.lock
2.52.0 is out now with a fix for the template inheritance issue so we can unpin the version again.
> Unpin view_component version

- .github/workflows/docs-workflow.yml
It doesn't have access to the necessary secrets by default.
> Skip docs preview deploy for dependabot

- design-system-docs/Gemfile
- design-system-docs/Gemfile.lock
- design-system-docs/bridgetown.config.yml
- design-system-docs/frontend/javascript/index.js
- design-system-docs/frontend/styles/_code.scss
- design-system-docs/frontend/styles/_examples.scss
- design-system-docs/frontend/styles/_feedback.scss
- design-system-docs/frontend/styles/_layout.scss
- design-system-docs/frontend/styles/index.scss
- design-system-docs/src/_cads_components/targeted_content.md
- design-system-docs/src/_component_docs/targeted-content.md
- design-system-docs/src/_component_examples/targeted_content_adviser.erb
- design-system-docs/src/_component_examples/targeted_content_default.erb
- design-system-docs/src/_components/shared/component_example.erb
- design-system-docs/src/_components/shared/component_example.rb
- design-system-docs/src/_layouts/component.erb
- design-system-docs/src/_pages/components.erb
- design-system-docs/src/_partials/_feedback_prompt.erb
Extracted from https://github.com/citizensadvice/design-system/pull/1874
Adds a basic component template and index page along with a ComponentExample view component which allows rendering a component example along with source code and generated HTML.
Opted not to extract the arguments table for now as I think that needs a little bit more thought.
> Add support for component examples

- .github/workflows/ci-workflow.yml
Pull requests from forks like https://github.com/citizensadvice/design-system/pull/1925 are not running any jobs. This is probably because we only trigger on the push event. It's likely we should be running on the `pull_request` event too.
> Run CI on pull_request event

- demo/config/application.rb
Component previews are already added to preview_paths by the engine code. We occasionally see odd load errors for some component previews and I wonder if it's because we were adding the preview paths twice. Either way, it's redundant so let's remove it.
> Avoid double adding previews

- src/ts/greedy-nav/GreedyNav.ts
Fixes: Greedy Nav doesn't close when tabbing out if no header links are present [NP-1755](https://citizensadvice.atlassian.net/jira/software/c/projects/NP/boards/208?modal=detail&selectedIssue=NP-1755&search=greedy)
> fix: closing greedy nav on tab out if there are no header links

- CHANGELOG.md
- engine/app/components/citizens_advice_components/asset_hyperlink.html.haml
- styleguide/examples/asset_hyperlink/example.html
We were migrating a corporate page[1] and when we ran an accessibility check we found that the icons used in asset download links don't read meaningfully to screenreaders[2]. And would be a possible fail at level A.
[1] https://cdn.develop.content.citizensadvice.org.uk/about-us/our-work/our-prevention-work/BESN
[2] https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html
> Asset hyperlink icons work with screen readers

- demo/Procfile.dev
- demo/bin/dev
- design-system-docs/bin/dev
Switching between the demo and docs site it would be useful to have a consistent start up script. A common Rails convention for this seems to be to have a `bin/dev` script.
**Bridgetown**
Adds a basic `bin/dev` script which delegates to `bin/bridgetown` start
**Demo app**
Adds a basic `bin/dev` script which uses foreman along with a Procfile to run the server and webpack-dev-server in a single command. Approach pinched from https://github.com/rails/cssbundling-rails
---
The upshot is that for each sub-project you can consistently run `bin/setup` to set up the project and `bin/dev` to start a dev server.
> Add consistent dev script for demo and docs site

- CHANGELOG.md
- package-lock.json
- package.json
Includes the following
**New**
🔗 Links: Document links no longer present their appended file icon to screen readers
🔗 Links: Relflow long links so they do not add scrollbars to the viewport
🔓 Disclosure: Adds new Disclosure view component
🥾 Footer: Add more flexible feedback_link slot and deprecate feedback_url argument.
🥾 Footer: Support external icon for column links and deprecateicon property. Previous option was too generic, only support external links.
🥾 Footer: Fix accessibility issue with external link icons using old icon font and reading out content. Use new SVG icons.
🛤️ Expand version ranges for citizens_advice_components to support Rails 7
**Bugfixes**
🔗 Links: Fix external link styles when used outside of the main [www.citizensadvice.org.uk](http://www.citizensadvice.org.uk/)[ …
> Release v5.3.0-alpha.0

- .github/workflows/docs-workflow.yml
- CONTRIBUTING.md
- contributing/adr/0004-only-run-docs-preview-build-when-a-label-is-added.md
- contributing/adr/README.md
- contributing/documentation-site.md
We currently run docs preview builds on all pull requests when they are opened or updated. This has a couple of trade-offs:
- Previews are generated for every PR which can add noise if you don't want one, or are not ready for one yet.
- Causes an error on pull requests from forks as the workflow doesn't have access to secrets
This pull request makes docs site previews opt-in by only running them when a label is added. Included the full context in an ADR added to this pull request.
> Run docs build only when a label is added

- design-system-docs/src/_pages/getting-started.md
Nice easy one. Was just a case of adding a new markdown file to `_pages`.
> Migrate getting started page

- design-system-docs/src/_foundations/breakpoints.md
Copying the breakpoints page from Storybook to Bridgetown. Removed the line about resizing the screen as noted in [the issue](https://github.com/citizensadvice/design-system/issues/1975)
> feat: adding breakpoints page

- design-system-docs/frontend/styles/_code.scss
Adds some basic inline code styles so they complement the existing block code examples.
> Add basic code styles to new docs site

- design-system-docs/src/_component_docs/targeted-content.md
- design-system-docs/src/_components/shared/arguments_table.rb
- design-system-docs/src/_data/component_arguments.yml
Extracts out a revised approach to component arguments tables from https://github.com/citizensadvice/design-system/pull/1874
Longer term we'd like to pull this data from yard or something similar, so using an approach that pulls from data files makes sense for now.
Makes a simple `_data/component_arguments.yml` file containing argument data and then extracts that within a shared component based on a key.
> Add support for component arguments table

- design-system-docs/frontend/styles/_sizing-border.scss
- design-system-docs/frontend/styles/_spacing-block.scss
- design-system-docs/frontend/styles/index.scss
- design-system-docs/src/_components/foundations/borders_table.rb
- design-system-docs/src/_components/foundations/spacing_table.rb
- design-system-docs/src/_foundations/spacing-and-sizing.md
Adding Spacing & Sizing page. Using the existing cads table component. Moved and renamed already existing css from the styleguide to the docs (i.e `_spacing-block.scss` and `_sizing-border.scss`)
> feat: adding spacing & sizing page

- design-system-docs/bridgetown.config.yml
- design-system-docs/frontend/styles/_examples.scss
- design-system-docs/frontend/styles/_foundations.scss
- design-system-docs/frontend/styles/index.scss
- design-system-docs/src/_component_docs/_defaults.yml
- design-system-docs/src/_component_docs/targeted-content.md
- design-system-docs/src/_component_examples/_defaults.yml
- design-system-docs/src/_component_examples/_foundations/_defaults.yml
- design-system-docs/src/_component_examples/_foundations/grid_basic.erb
- design-system-docs/src/_component_examples/_foundations/grid_multi_column.erb
- design-system-docs/src/_component_examples/_foundations/grid_responsive.erb
- design-system-docs/src/_component_examples/_targeted_content/_defaults.yml
- design-system-docs/src/_component_examples/_targeted_content/adviser.erb
- design-system-docs/src/_component_examples/_targeted_content/default.erb
- design-system-docs/src/_components/shared/component_example.erb
- design-system-docs/src/_components/shared/component_example.rb
- design-system-docs/src/_foundations/grid.md
- design-system-docs/src/_layouts/component_example.erb
Migrates the grid foundations page to the new docs site. Closes #1973
Includes some notable changes to the component examples to allow us to decide whether to show html or erb source samples:
- Allow component examples to be grouped by category
- Allow option to show just HTML or just ERB source
- Update styles to improve boundary between example UI and the example itself
- Add a minimal component example layout
> Migrate Grid foundations

- engine/spec/components/citizens_advice_components/asset_hyperlink_spec.rb
- engine/spec/components/citizens_advice_components/badge_spec.rb
- engine/spec/components/citizens_advice_components/button_spec.rb
- engine/spec/components/citizens_advice_components/contact_details_spec.rb
- engine/spec/components/citizens_advice_components/footer_spec.rb
- engine/spec/components/citizens_advice_components/page_review_spec.rb
- engine/spec/components/citizens_advice_components/table_spec.rb
As of the latest version of view_component `rendered_component` was renamed to `rendered_content` and subsequently marked as deprecated.
Apparently the intent was for this to be a private method and for tests to prefer using the capybara `page` method.
Most of our tests already do this, so replace all remaining uses of `rendered_content` with `page`.
> Use capybara page method in tests

- CHANGELOG.md
- engine/app/components/citizens_advice_components/table.html.haml
- engine/spec/components/citizens_advice_components/__snapshots__/table.snap
- styleguide/examples/sample_pages/content-sample.html
- styleguide/examples/table/example.html
- styleguide/examples/table/long_table.html
- styleguide/examples/table/no_caption.html
- styleguide/examples/targeted_content/adviser.html
I've been working with tables a lot this week and noticed that our markup is back to front 🙈 
Previously the thead was being rendered within the tbody. This is invalid according to the spec, a thead should always be outside the tbody.
> Fix invalid table markup

- .prettierignore
- design-system-docs/Gemfile
- design-system-docs/frontend/styles/_foundations.scss
- design-system-docs/package.json
- design-system-docs/src/_components/shared/colour_table.rb
- design-system-docs/src/_data/colour_language.json
- design-system-docs/src/_foundations/colours.md
- design-system-docs/yarn.lock
Uses sass-export to export a json representation of the colour language to src/_data which is made available within bridgetown. This lets us port the equivalent colour tables from storybook.
This data file will need syncing with `npm run update-colour-language` if we change the values but this happens infrequently enough that this is fine to do manually when that happens.
> Add full colour foundations page

- CHANGELOG.md
- engine/app/components/citizens_advice_components/table.html.haml
- engine/spec/components/citizens_advice_components/__snapshots__/table.snap
Extracted from https://github.com/citizensadvice/design-system/pull/2099. Flagged by cypress-html-validate.
From https://webaim.org/techniques/tables/data#headers
> All <th> elements should generally always have a scope attribute. While screen readers may correctly guess whether a header is a column header or a row header based on the table layout, assigning a scope makes this unambiguous.
> Tables: Add scope to th cells

- engine/Gemfile
- engine/Gemfile.lock
- engine/spec/components/citizens_advice_components/breadcrumbs_spec.rb
- engine/spec/components/citizens_advice_components/input_spec.rb
- engine/spec/components/citizens_advice_components/pagination_spec.rb
- engine/spec/components/citizens_advice_components/textarea_spec.rb
Batches up all engine related dependabot updates and auto-fixes some rubocop warnings from the latest version of citizens-advice-style.
> Update engine deps

- CHANGELOG.md
- engine/app/components/citizens_advice_components/pagination.html.haml
- styleguide/examples/pagination/with_fifth_page.html
- styleguide/examples/pagination/with_first_page.html
- styleguide/examples/pagination/with_last_page.html
- styleguide/examples/pagination/with_second_page.html
- styleguide/examples/pagination/with_tenth_page.html
A role of navigation is implied when using the nav element. Flagged by cypress-html-validate as part of https://github.com/citizensadvice/design-system/pull/2099
> Pagination: Remove redundant role

- CHANGELOG.md
- engine/app/components/citizens_advice_components/header.html.haml
- engine/spec/components/citizens_advice_components/header_spec.rb
- scss/6-components/_header.scss
- scss/6-components/_search.scss
- src/ts/header/header.test.ts
- src/ts/header/header.ts
- styleguide/examples/header/full_example.html
- styleguide/examples/header/minimal.html
- styleguide/examples/header/with_custom_account_link.html
- styleguide/examples/header/with_custom_logo.html
- styleguide/examples/header/with_navigation.html
- styleguide/examples/sample_pages/content-sample.html
- styleguide/examples/sample_pages/form-sample.html
Prompted by https://github.com/citizensadvice/design-system/pull/2099 this PR attempts to fix a few accesibility and markup quality issues with the header search toggle:
1. Was using title rather than aria-label for the description
2. Was missing a type attribute on the button element
3. Was missing aria-controls to associate the button with the search
4. Both the toggle and the search form were using icon fonts which causes additional text to be read out when interacting with either element. Switch to use SVG icons. See https://github.com/citizensadvice/design-system/issues/1902
> Header: Fix issues with search toggle in header

- CHANGELOG.md
- engine/app/components/citizens_advice_components/on_this_page.html.haml
- styleguide/examples/on_this_page/with_nested_links.html
Extracted from https://github.com/citizensadvice/design-system/pull/2099
Buttons should have an explicit type
> On this page: Add missing button type

- design-system-docs/src/_component_docs/asset-hyperlink.md
- design-system-docs/src/_component_examples/_asset_hyperlink/_defaults.yml
- design-system-docs/src/_component_examples/_asset_hyperlink/default.erb
- design-system-docs/src/_data/component_arguments.yml
Two questions that will potentially go into separate PRs:
- Should we include 'On this page' for the foundation pages as well?
- Should I remove the external icon after the hyperlink?
> Adding Asset hyperlink to the new docs site

- design-system-docs/frontend/javascript/index.js
- design-system-docs/src/_layouts/component_example.erb
- design-system-docs/src/_layouts/default.erb
Adds no-js support to the docs site, based on the same model as public website:
- add `html.no-js` to the default layout
- remove it again in a `script` block in the `head`
- add some error handling in the main js file
> feat: add no-js support

- design-system-docs/src/_foundations/_defaults.yml
- design-system-docs/src/_layouts/foundations.erb
Originated from https://github.com/citizensadvice/design-system/pull/2157 where we discussed adding 'On this page' section to the foundations pages.
> Feat: adding 'On this page' section to foundations

- design-system-docs/frontend/javascript/index.js
- design-system-docs/frontend/styles/index.scss
- design-system-docs/package.json
Currently running `yarn install` in the docs package take a long time to resolve the design-system using the `file:` install method. I also tried using `link:` to install the package which should use a simple symlink. In both cases the install stalls for a long time, presumably because the mode module is at the root of the project so it's getting confused with some circular behaviour.
Either way linking using relative paths has exactly the same effect locally, we don't actually need to install the package. Switching to relative paths fixes any install issues.
> Docs: Speed up yarn installs

- .github/workflows/ci-workflow.yml
- demo/config/environments/test.rb
In https://github.com/citizensadvice/design-system/pull/2210 we made some changes to improve the reliability of the Backstop tests.
One of those changes was to run the app in production mode. It turns out that this:
a) isn't necessary, the real fix was waiting on a specific component URL before running the tests and
b) whilst main branch builds work fine for normal pull requests they fail for dependabot changes because it doesn't have access to the secret used for SECRET_KEY_BASE.
As it's not actually necessary to run in production mode let's swap back to test mode but with eager-loading enabled in CI which should do the job without breaking on dependabot changes.
> Run Backstop tests in test mode again

- CHANGELOG.md
Moved a breaking change to bugfix as it would potentially happen when not using Rails.
Unblocks pre-releasing design-system  v5.4
> chore: updating changelog before pre-release

- CHANGELOG.md
Removing 'unreleased' line from changelong after a pre-release
> fix: removed unreleased line from changelog

- CHANGELOG.md
- engine/app/components/citizens_advice_components/header.html.erb
- engine/app/components/citizens_advice_components/header.rb
- engine/spec/components/citizens_advice_components/header_spec.rb
Extracted from https://github.com/citizensadvice/design-system/pull/2251
Only applies to the Rails engine header component. When rendering the header with only the logo slot the markup for the secondary column is still output. Only render the extra markup when needed.
Best viewed with whitespace ignored: https://github.com/citizensadvice/design-system/pull/2275/files?w=1
> Header: Only render right column when needed

- CHANGELOG.md
- scss/1-settings/_colour-language.scss
- scss/6-components/_navigation.scss
Extracted from https://github.com/citizensadvice/design-system/pull/2251
Currently the colour of the navigation is controlled by the primary brand colour. This is a problem if you need to control the colour of the navigation without changing the brand colour as is the case in https://github.com/citizensadvice/design-system/pull/2251
Update the navigation styles to use a dedicated variable for the navigation background colour.
@marianayovcheva Just an FYI that we'll probably need to reconcile things whenever we pick https://github.com/citizensadvice/design-system/pull/1863 back up again
> Navigation: Add background to colour language

- scss/6-components/_footer.scss
- scss/6-components/_header.scss
Had a go at using https://github.com/citizensadvice/design-system/pull/1863 to re-theme the intranet. It worked really well and allowed me to remove a bunch of previous override and configure fewer variables. Spotted two small details along the way:
1. The footer was still using an old colour variable name which broke when switching to the new variables
2. Link state ordering in the header caused some undesirable conflicts when theming. See the commit message in https://github.com/citizensadvice/design-system/commit/f5ecdee7d254102bfd31431c4a5c8272d06d90d0 for more detail
> Rationalise colour names amends

- CHANGELOG.md
- design-system-docs/src/_foundations/typography.md
- design-system-docs/src/_layouts/component.erb
- scss/5-objects/_prose.scss
Often we use the cads-prose class for content where we also embed lots of rich components inside. By default styles within cads-prose cascade down which can subtly affect any components inside. We often work around this in our styles by resetting styles if we are inside a cads-prose element.
I'm proposing that we introduce a new cads-prose-scoped class which uses a child combinator selector to only apply typographic styles to immediate children. Any components within a scoped prose block would not be effected as they would start a new context.
I think the way our standard cads-prose class behaves is a sensible default but it is useful to have an equivalent class that is more targeted for cases where we need a bit more control.
---
Notably using the child combinator in combination with an …
> Introduce the concept of scoped prose styles

- design-system-docs/frontend/styles/_code.scss
- design-system-docs/src/_component_docs/asset-hyperlink.md
- design-system-docs/src/_component_docs/breadcrumbs.md
- design-system-docs/src/_component_docs/button.md
- design-system-docs/src/_component_docs/radio-group.md
- design-system-docs/src/_component_docs/targeted-content.md
- design-system-docs/src/_component_examples/_radio_group/default.erb
- design-system-docs/src/_component_examples/_radio_group/error.erb
- design-system-docs/src/_component_examples/_targeted_content/default.erb
- design-system-docs/src/_components/shared/component_example.erb
- design-system-docs/src/_components/shared/component_example.rb
- design-system-docs/src/_components/shared/component_example_presenter.rb
- design-system-docs/src/_components/shared/component_example_source.erb
- design-system-docs/src/_components/shared/component_example_source.rb
1. **Adds a new ComponentExampleSource component**. Serves a similar purpose to ComponentExample but just renders the ERB source code. Useful for showing inline code samples that reuse our existing code samples.
2. **Share code sample code between components**. Both the source and full example components use the same underlying data. Provide a presenter-ish object which can also find an example based on the site, category, and slug. Provides a shared interface for accessing an example with pre-transformed and formatted source.
The upshot is you can call this from your component docs:
```
<%= render(Shared::ComponentExampleSource.new(:asset_hyperlink, :default)) %>
```
And it will render just the inline source for the provided example
> Add new ComponentExampleSource component

- scss/2-tools/__tests__/grid.test.js
- scss/2-tools/_grid.scss
- scss/2-tools/tools-imports.scss
- scss/5-objects/_grid.scss
Adds a new cads-grid-col-width function which allows us to get the
percentage width for a given number of grid columns.
```scss
.my-component {
max-width: cads-grid-col-width(6);
}
```
Throws an error if you request a column count greater than the maximum.
> Add new cads-grid-col-width function

- design-system-docs/frontend/javascript/examples.js
- design-system-docs/frontend/javascript/index.js
- design-system-docs/src/_component_examples/_icons/_defaults.yml
- design-system-docs/src/_component_examples/_icons/plus_minus.erb
- design-system-docs/src/_component_examples/_icons/up_down.erb
- design-system-docs/src/_components/foundations/icon_grid.erb
- design-system-docs/src/_data/component_arguments.yml
- design-system-docs/src/_foundations/icons.md
As the foundations icons page now uses our SVG icon components I thought it made sense to merge the two icons pages together. Previously the component version referenced the foundations page quite a bit anyway.
> Migrate SVG Icons page to new component docs

- design-system-docs/frontend/javascript/examples.js
- design-system-docs/frontend/styles/_code.scss
- design-system-docs/frontend/styles/_examples.scss
- design-system-docs/src/_component_docs/notice-banner.md
- design-system-docs/src/_component_docs/page-review.md
- design-system-docs/src/_component_docs/pagination.md
- design-system-docs/src/_component_docs/success-message.md
- design-system-docs/src/_component_examples/_notice_banner/_defaults.yml
- design-system-docs/src/_component_examples/_notice_banner/default.erb
- design-system-docs/src/_component_examples/_page_review/_defaults.yml
- design-system-docs/src/_component_examples/_page_review/default.erb
- design-system-docs/src/_component_examples/_pagination/_defaults.yml
- design-system-docs/src/_component_examples/_pagination/default.erb
- design-system-docs/src/_component_examples/_success_message/_defaults.yml
- design-system-docs/src/_component_examples/_success_message/default.erb
- design-system-docs/src/_data/component_arguments.yml
- engine/app/components/citizens_advice_components/notice_banner.html.erb
- engine/app/components/citizens_advice_components/notice_banner.html.haml
Using the new ComponentExampleSource component from https://github.com/citizensadvice/design-system/pull/2304 this PR migrates over a few of the simpler component docs pages.
1. Notice banner (converts component to ERB in the process)
2. Success message
3. Page review
4. Pagination
> Migrate more component docs pages

- design-system-docs/src/_component_docs/tables.md
- design-system-docs/src/_component_examples/_tables/_defaults.yml
- design-system-docs/src/_component_examples/_tables/default.erb
- design-system-docs/src/_data/component_arguments.yml
Migrate table docs using the generator introduced in https://github.com/citizensadvice/design-system/pull/2303
Ended up dropping the extra examples from the docs:
1. The long table example is more of a stress test and is already included in our backstop tests which makes more sense
2. The no-caption option is not _really_ recommended—we ideally want you to always provide a caption for accessibility reasons—but is covered by the components arguments table as an optional argument.
> Migrate table docs

- design-system-docs/src/_component_docs/search.md
- design-system-docs/src/_component_examples/_search/_defaults.yml
- design-system-docs/src/_component_examples/_search/default.erb
- design-system-docs/src/_component_examples/_search/with_value.erb
- design-system-docs/src/_data/component_arguments.yml
Not to toot my own 🎺 but the new docs generator makes this process _so_ much quicker.
> Migrate search component docs

- design-system-docs/frontend/javascript/index.js
- design-system-docs/frontend/javascript/theme.js
- design-system-docs/src/_component_docs/on-this-page.md
- design-system-docs/src/_component_examples/_on_this_page/_defaults.yml
- design-system-docs/src/_component_examples/_on_this_page/default.erb
- design-system-docs/src/_component_examples/_on_this_page/with_nested_links.erb
- design-system-docs/src/_data/component_arguments.yml
Migrate on this page component docs. Split the component arguments out into two tables to better reflect the fact some are top-level the rest are for a slot.
> Migrate on this page component docs

- engine/app/components/citizens_advice_components/asset_hyperlink.html.erb
- engine/app/components/citizens_advice_components/asset_hyperlink.html.haml
- engine/app/components/citizens_advice_components/asset_hyperlink.rb
Convert asset hyperlink to ERB. Removes some of the awkward HAML-escaping needed for this component and pushes more of the detail into the component class.
> Convert asset hyperlink to ERB

- contributing/release-process.md
Updates the release process docs after doing my first alpha release in a while to:
1. More clearly spell out the prerequisites to publish
2. Vary the instructions based on if the release is a pre-release to encourage running npm publish with --tag latest as the dist-tag
3. Reflect the fact that the release script now uses `--no-git-tag-version` (see https://github.com/citizensadvice/design-system/pull/1818) so we need to create the tag as part of the GitHub release
> Update release process docs

- design-system-docs/src/_component_docs/header.md
- design-system-docs/src/_component_docs/navigation.md
- design-system-docs/src/_component_examples/_header/with_navigation.erb
- design-system-docs/src/_component_examples/_navigation/_defaults.yml
- design-system-docs/src/_component_examples/_navigation/default.erb
- design-system-docs/src/_data/component_arguments.yml
Migrates the navigation component docs with a couple of amends:
1. Adds a navigation example to the header docs. I debated merging these docs into a single page but instead cross-linked between the two
2. Added missing JavaScript documentation to the navigation page
> Migrate navigation component docs

- CHANGELOG.md
- design-system-docs/src/_layouts/basic.erb
- design-system-docs/src/_layouts/component.erb
- design-system-docs/src/_layouts/default.erb
- design-system-docs/src/_layouts/foundations.erb
- design-system-docs/src/_pages/components.erb
- design-system-docs/src/_pages/foundations.erb
- design-system-docs/src/_partials/_notice_banner.erb
- scss/6-components/_navigation_greedy-nav.scss
Small bits of tidy up after migrating most of the component docs:
- Greedy nav: Use theme colour
- Preload fonts in docs website
- Disable telephone format detection
- Fix accessibility warning with notice banner outside main landmark
> Docs tidy up

- design-system-docs/src/_component_docs/text-input.md
- design-system-docs/src/_component_docs/textarea.md
- design-system-docs/src/_component_examples/_text_input/_defaults.yml
- design-system-docs/src/_component_examples/_text_input/all_options.erb
- design-system-docs/src/_component_examples/_text_input/default.erb
- design-system-docs/src/_component_examples/_text_input/fixed_widths.erb
- design-system-docs/src/_component_examples/_text_input/optional.erb
- design-system-docs/src/_component_examples/_text_input/with_custom_type.erb
- design-system-docs/src/_component_examples/_text_input/with_error_message.erb
- design-system-docs/src/_component_examples/_text_input/with_hint_text.erb
- design-system-docs/src/_component_examples/_text_input/with_value.erb
- design-system-docs/src/_component_examples/_textarea/_defaults.yml
- design-system-docs/src/_component_examples/_textarea/all_options.erb
- design-system-docs/src/_component_examples/_textarea/default.erb
- design-system-docs/src/_component_examples/_textarea/optional.erb
- design-system-docs/src/_component_examples/_textarea/with_error_message.erb
- design-system-docs/src/_component_examples/_textarea/with_hint.erb
- design-system-docs/src/_component_examples/_textarea/with_value.erb
- design-system-docs/src/_data/component_arguments.yml
Migrate text input and textarea component docs to new website.
Renamed the "Input" docs to "Text input" to reflect that's the actual component name used here.
> Migrate text input and textarea component docs

- package-lock.json
- package.json
Noticed that size-limit has stopped working for our JS files (always reporting 0 B).
Uses this as an excuse to upgrade size-limit to the latest version. The latest version uses esbuild now for size-limit/preset small-lib which doesn't make sense for our css files. All we really care about is a file-size check so switches the setup to use the basic file plugin and updates the glob for our JS files to include everything, not just top-level files.
```
> size-limit
lib/lib.css
Size limit: 16 kB
Size:       12.56 kB gzipped
lib/error-summary.js, lib/header.js, lib/targeted-content.js, lib/disclosure/disclosure.js, lib/greedy-nav/Config.js, lib/greedy-nav/GreedyNav.js, lib/greedy-nav/index.js, lib/on-this-page/on-this-page.js, lib/utils/show-hide.js
Size limit: 16 kB
Size:       12.23 kB …
```
> Upgrade size-limit dependencies

- engine/app/components/citizens_advice_components/targeted_content.html.erb
- engine/app/components/citizens_advice_components/targeted_content.html.haml
- engine/app/components/citizens_advice_components/targeted_content.rb
- styleguide/examples/sample_pages/content-sample.html
- styleguide/examples/targeted_content/adviser.html
- styleguide/examples/targeted_content/anchor.html
- styleguide/examples/targeted_content/default.html
Convert targeted content to ERB. Made the choice to move the attributes into the template as ERB has far less of a problem with larger lists of attributes so it's clearer having them inline now.
> Convert targeted content to ERB

- .github/workflows/docs-workflow-main.yml
Currently our docs build workflow only publishes drafts and on release versions.
Whilst we are still working on the foundations of the new docs website it would be nice to have a continuously deployed version of the latest changes. Added a new workflow that publishes on main builds which we can remove later if we want to stick to release-only builds.
> Publish docs on main build

- package-lock.json
- package.json
- scripts/release.js
We currently use moment to format a single date in our changelog script. We can reasonably use `Intl.DateTimeFormat` here instead. Updates the script to:
- Use `Intl.DateTimeFormat` in place of moment
- Simplify the formatting of heading so there's less special case formatting and so that heading levels aren't skipped awkwardly.
> Remove moment as a dependency

- engine/app/components/citizens_advice_components/disclosure.html.erb
- engine/app/components/citizens_advice_components/disclosure.html.haml
- engine/app/components/citizens_advice_components/disclosure.rb
- styleguide/examples/disclosure/example.html
- styleguide/examples/disclosure/with_additional_attributes.html
- styleguide/examples/disclosure/with_optional_id.html
- styleguide/examples/disclosure/without_open_summary.html
- styleguide/examples/sample_pages/content-sample.html
- styleguide/examples/targeted_content/adviser.html
- styleguide/examples/targeted_content/anchor.html
- styleguide/examples/targeted_content/default.html
Converts disclosure component to use an ERB template. Tidies up the component class in the process, mostly to flatten the button attributes.
> Convert disclosure to ERB

- CHANGELOG.md
- package-lock.json
- package.json
Realised I probably should've gone for `5.5.0-alpha` in the previous pre-release.
> v5.5.0-alpha.0

- design-system-docs/frontend/styles/standalone.scss
- design-system-docs/src/_component_examples/_checkbox/_defaults.yml
- design-system-docs/src/_component_examples/_checkbox_group/_defaults.yml
- design-system-docs/src/_component_examples/_radio_group/_defaults.yml
- design-system-docs/src/_component_examples/_search/_defaults.yml
- design-system-docs/src/_component_examples/_text_input/_defaults.yml
- design-system-docs/src/_component_examples/_textarea/_defaults.yml
- design-system-docs/src/_components/shared/component_example.erb
- design-system-docs/src/_components/shared/component_example_presenter.rb
- design-system-docs/src/_layouts/component_example.erb
Our form component examples weren't wrapped in a `<form>` element. A form context affects how screen readers behave. Rather than adding a form manually to every component I've added an option to the front-matter to optionally add the form in, also set novalidate as we do not rely on html validation for our forms so we don't want this behaviour.
Whilst I'm here makes a small change to the standalone component example styles to add a bit of padding to the body aside from global components (this is the same approach we use in the demo app)
> Wrap form examples in a form context

- CHANGELOG.md
- design-system-docs/frontend/javascript/components/component-examples.js
- design-system-docs/frontend/styles/_examples.scss
- design-system-docs/frontend/styles/_foundations.scss
- design-system-docs/frontend/styles/_settings.scss
- design-system-docs/frontend/styles/standalone.scss
- design-system-docs/src/_components/foundations/borders_table.rb
- design-system-docs/src/_components/foundations/spacing_table.rb
- scss/1-settings/_colour-language.scss
- scss/2-tools/_interactive-elements.scss
- Move example grid styles into standalone styles
- Fix spacing and sizing example tables
- Update component examples to match latest designs
- Disable iframeResizer logging
- Make nav link colours customisable
- Update docs header colours to match designs
> Docs design refinement

- CHANGELOG.md
- engine/.rubocop.yml
- engine/app/components/citizens_advice_components/checkable/base.rb
- engine/spec/components/citizens_advice_components/checkbox_single_spec.rb
When running against ruby 3 and passing extra options to a checkbox via `c.checkbox(label: "Label", value: "value", extra: "example")` the previous `**additional_attributes` keyword args would include the named label which we don't want.
This is down to the `super` call in the initialise method. Calls to super in subclasses of `ViewComponent::Base` aren't needed by default and can change the behaviour of `**kwargs` so we exclude component classes from this rule.
> Fix label being assigned as checkbox attribute in Ruby 3

- design-system-docs/src/_component_docs/asset-hyperlink.md
- design-system-docs/src/_component_docs/breadcrumbs.md
- design-system-docs/src/_component_docs/button.md
- design-system-docs/src/_component_docs/callout.md
- design-system-docs/src/_component_docs/error-summary.md
- design-system-docs/src/_component_docs/notice-banner.md
- design-system-docs/src/_component_docs/page-review.md
- design-system-docs/src/_component_docs/pagination.md
- design-system-docs/src/_component_docs/radio-group.md
- design-system-docs/src/_component_docs/success-message.md
- design-system-docs/src/_foundations/icons.md
- design-system-docs/src/_foundations/typography.md
- design-system-docs/src/_pages/docs-roadmap.md
- design-system-docs/src/_partials/_notice_banner.erb
- scripts/release.js
A few last bits of prep before we launch the new docs website:
- Don't build storybook docs on release — We won't need this anymore and new docs builds are handled via CI
- Add minimal docs roadmap page, just enough to link to from the notice banner.
- Fix some wording and typos based on the documentation review
> Design system docs launch prep

- demo/Gemfile.lock
- design-system-docs/Gemfile
- design-system-docs/Gemfile.lock
- engine/Gemfile.lock
- engine/citizens_advice_components.gemspec
Pin rails-i18n to 7.0.5 as 7.0.6 removes welsh language locales due to lack of support. We only use these locales for basic date formats so we could inline the parts we need and remove this dependency in future.
Fixes the broken build.
> Pin rails-i18n version

- engine/.rubocop.yml
- engine/Gemfile
- engine/Gemfile.lock
- engine/spec/components/citizens_advice_components/badge_spec.rb
- engine/spec/components/citizens_advice_components/breadcrumbs_spec.rb
- engine/spec/components/citizens_advice_components/callout_spec.rb
- engine/spec/components/citizens_advice_components/checkbox_group_spec.rb
- engine/spec/components/citizens_advice_components/checkbox_single_spec.rb
- engine/spec/components/citizens_advice_components/contact_details_spec.rb
- engine/spec/components/citizens_advice_components/disclosure_spec.rb
- engine/spec/components/citizens_advice_components/error_summary_spec.rb
- engine/spec/components/citizens_advice_components/header_spec.rb
- engine/spec/components/citizens_advice_components/input_spec.rb
- engine/spec/components/citizens_advice_components/navigation_spec.rb
- engine/spec/components/citizens_advice_components/notice_banner_spec.rb
- engine/spec/components/citizens_advice_components/on_this_page_spec.rb
- engine/spec/components/citizens_advice_components/page_review_spec.rb
- engine/spec/components/citizens_advice_components/pagination_spec.rb
- engine/spec/components/citizens_advice_components/radio_group_spec.rb
- engine/spec/components/citizens_advice_components/search_spec.rb
- engine/spec/components/citizens_advice_components/section_links_spec.rb
- engine/spec/components/citizens_advice_components/success_message_spec.rb
- engine/spec/components/citizens_advice_components/table_spec.rb
- engine/spec/components/citizens_advice_components/targeted_content_spec.rb
- engine/spec/components/citizens_advice_components/text_input_spec.rb
- engine/spec/components/citizens_advice_components/textarea_spec.rb
- engine/spec/spec_helper.rb
Does a bit of clean up on the component specs, mainly to:
1. Convert remaining specs to use capybara matchers
2. Fix rubocop warnings in locale specific tests
3. Clarify any scenarios where the previous specs were misleading
Includes a few notable updates:
**Checkbox group specs**
Splits out the optional arguments scenarios into multiple blocks. In the process clarifies that the layout and size options don't apply to checkbox groups, only radio groups.
**Radio group specs**
Expands specs to cover the same scenarios as checkbox groups. Whilst they inherit a base class they are ultimately separate interfaces so we should test both fully. Expands specs for layout and size options which are unique to radio groups.
**Text input and textarea specs**
Expands text input and textarea specs to …
> Clean up component specs

- .nvmrc
- demo/backstop-test-url.js
- package-lock.json
The latest LTS version of Node is now v18. Update the nvmrc file and upgrade the package-lock version (format changed in recent npm versions).
> Upgrade to node v18

- .github/workflows/ci-workflow.yml
There's a downstream issue with the edge version of rails that is causing our builds to fail.
Given that for our use case we have a relatively small number of known consumers and know the exact rails versions they all run we probably don't need to be testing against the bleeding-edge version of rails.
Removing it should fix the current build failures.
> Remove rails main from test matrix

- .prettierignore
- CHANGELOG.md
- demo/Gemfile.lock
- design-system-docs/Gemfile.lock
- engine/Gemfile.lock
- engine/citizens_advice_components.gemspec
- engine/config/i18n-tasks.yml
- engine/config/locales/cy.yml
- engine/lib/citizens_advice_components/engine.rb
- engine/spec/i18n_spec.rb
The rails-i18n gem historically provided these but the cy locale was removed in 7.0.6 due to lack of support. See https://github.com/svenfuchs/rails-i18n/pull/1007
As we only need a small set of translations for date formatted provided by design system components we bundle the necessary translations ourselves.
Fixes #2478
> Bundle Welsh translations for date formats

- design-system-docs/Gemfile
- design-system-docs/Gemfile.lock
- engine/Gemfile.lock
Updates the pinned version of viewcomponent to specify anything after 2.82.0 which fixes the regression when used outside of Rails.
> Docs: Update viewcomponent version

- .prettierignore
- design-system-docs/src/google72951c9396a77d88.html
We've been having some alerts about dangerous content from Chrome and Firefox. We can use google search console to investigate and submit our site for review. We need to verify the site ownership. I'm not 100% this will work because we're currently using netlify subdomain, but I want to try to see what will happen with HTML file upload for verification. I'll remove the file once we finish the verification.
> feat: trying to verify google search console

- design-system-docs/yarn.lock
- package-lock.json
This was closed in https://github.com/citizensadvice/design-system/pull/2680 but we want to apply this upgrade to fix a dependabot warning.
> Upgrade minimist to fix vulnerability notification

- demo/app/components/form_app_header_component.html.erb
- design-system-docs/src/_component_docs/header.md
The examples and demo code for using a custom `account_link` were misleading as they continued to pass arguments to the method as well as providing a block.
When providing a block this arguments are ignored. Updated the example and demo code to reflect this.
Spotted whilst pairing with @pksterling
> Remove misleading arguments in header examples

- engine/.rubocop.yml
- Removes rubocop-rspec from the require list as this is included by default by citizens-advice-style
- Disable SuggestExtensions flag
- Remove redundant CountAsOne rules that are included in citizens-advice-style now
> Revise rubocop config

- .github/CODEOWNERS
Ensures cnorthwood is able to approve PRs as CODEOWNER for the repository.
> Amend CODEOWNERS

- .github/dependabot.yml
Now that dependabot groups are in general availability we can try configuring them for a few things.
https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/
Start with rules for the testing tools that have a few related packages (eslint, stylelint, jest)
> Add dependabot groups for common dev-dependencies

- .github/workflows/ci-workflow.yml
Current CI version constraint has started matching Rails 7.1 which is now out. Make sure the range covers 7.0.x explicitly. We'll need to add Rails 7.1 to the build matrix and fix any issues but this gets the build passing.
> Fix Rails 7.0.x CI version constraint

- .github/CODEOWNERS
Use the design-system-owners team to manage CODEOWNERS
> Consolidate CODEOWNERS

- CHANGELOG.md
- design-system-docs/src/_data/component_arguments.yml
- engine/app/components/citizens_advice_components/callout.html.erb
- engine/app/components/citizens_advice_components/callout.rb
- engine/spec/components/citizens_advice_components/callout_spec.rb
The `title` attribute in the callout component was used as an `aria-label` for its container.
This is being changed because:
- The callout container is a non-interactive element and `aria-label` is intended for use on interactive elements only (as described in the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label))
- Allowing only one attribute to be passed for a specific option in the container element is quite restrictive
The following changes have been made:
- A deprecation warning has now been added to the use of `title` in the callout component
- `attributes` is now an optional attribute that passes a hash of options to the callout component element
> Callout: Replace `title` with `attributes`

- engine/app/components/citizens_advice_components/callout.rb
- engine/app/components/citizens_advice_components/footer.rb
- engine/app/components/citizens_advice_components/section_links.rb
- engine/lib/citizens_advice_components.rb
- engine/lib/citizens_advice_components/engine.rb
- engine/spec/components/citizens_advice_components/callout_spec.rb
- engine/spec/components/citizens_advice_components/footer_spec.rb
- engine/spec/components/citizens_advice_components/section_links_spec.rb
In the latest version of Rails there is a deprecation warning raised when using `ActiveSupport::Deprecation.warn`, specifically:
```
Calling warn on ActiveSupport::Deprecation is deprecated and will be removed from Rails
```
From the Rails 7.1 release notes
> All usage of `ActiveSupport::Deprecation` as a singleton is deprecated,
> the most common one being `ActiveSupport::Deprecation.warn`.
> Gem authors should now create their own deprecator (`ActiveSupport::Deprecation` object),
> and use it to emit deprecation warnings.
This updates our code to create a library specific deprecator instance with a deprecation horizon of v6.0.
It also configures the new `Rails.application.deprecators` method to allow applications to control our library specific deprecation warnings.
See:
- …
> Add library specific deprecator

- demo/config/environments/development.rb
- demo/config/environments/test.rb
Following on from https://github.com/citizensadvice/design-system/pull/3074 configure the demo application to raise on deprecations in development and test environments to ensure that any example code isn't using deprecated design system arguments or methods.
Includes a failing commit (https://github.com/citizensadvice/design-system/pull/3075/commits/7edbe80dd172bdff31392763469ccdd123f8c955) which will be removed from this PR once it has demonstrated that CI fails when a component preview contains a deprecated argument.
See: https://github.com/citizensadvice/design-system/actions/runs/6801856332/job/18493622727?pr=3075#step:11:62
Fails via the Cypress accessibility smoke-test because that's what actually loads every single component example which is a _little_ counter intuitive but the a) …
> Raise deprecations in demo app

- .github/workflows/ci-workflow.yml
Ruby 3.3 is out now so we can add it to the test matrix.
> Add Ruby 3.3 to test matrix

- CHANGELOG.md
- design-system-docs/src/_component_examples/_select/default.erb
- design-system-docs/src/_component_examples/_select/optional.erb
- design-system-docs/src/_component_examples/_select/with_error.erb
- design-system-docs/src/_component_examples/_select/with_hint_text.erb
- design-system-docs/src/_component_examples/_select/with_value.erb
- engine/app/components/citizens_advice_components/select.rb
- engine/spec/components/citizens_advice_components/select_spec.rb
This was only needed because `CitizensAdviceComponents::Select` inherits from `CitizensAdviceComponents::Input` which does require a `type`.
Instead, we pass `type: nil` by default into the initialiser.
> Remove unused `type` option from select component

- .github/workflows/ci-workflow.yml
- CHANGELOG.md
- engine/.rubocop.yml
- engine/citizens_advice_components.gemspec
Ruby 3.0.x is due to go [end-of-life on 31 March 2024](https://endoflife.date/ruby).
To prepare for this:
1. Increase the minimum supported Ruby version to 3.1.x
2. Remove Ruby 3.0.x from our CI matrix
3. Update our rubocop rules to reflect changes in the minimum version
Raising this ahead of time but we can hold off on merging this until closer to the EOL date.
> Increase minimum Ruby version to 3.1.x

- CHANGELOG.md
- engine/app/components/citizens_advice_components/footer.rb
- engine/config/locales/cy.yml
- engine/config/locales/en.yml
- engine/spec/components/citizens_advice_components/footer_spec.rb
This has been implemented to check the current date and return the new registered office from moving day onwards.
> update footer component fallback legal text to reflect registered office move

- CHANGELOG.md
- engine/app/components/citizens_advice_components/footer.rb
- engine/spec/components/citizens_advice_components/footer_spec.rb
Adding `legal_summary_default` method which is reused in `legal_summary_feedback` (if no `legal_summary` slot is added) and if a `legal_summary` slot exists but is empty.
> fix: commonise legal summary

- CHANGELOG.md
- engine/app/components/citizens_advice_components/footer.rb
- engine/config/locales/cy.yml
- engine/config/locales/en.yml
- engine/spec/components/citizens_advice_components/footer_spec.rb
The office move date has now passed we can remove the conditional logic and only ship the new office address.
> Remove conditional footer logic

- CHANGELOG.md
- design-system-docs/src/_data/component_arguments.yml
- engine/app/components/citizens_advice_components/callout.rb
- engine/app/components/citizens_advice_components/footer.html.erb
- engine/app/components/citizens_advice_components/footer.rb
- engine/app/components/citizens_advice_components/section_links.html.erb
- engine/app/components/citizens_advice_components/section_links.rb
- engine/spec/components/citizens_advice_components/callout_spec.rb
- engine/spec/components/citizens_advice_components/footer_spec.rb
- engine/spec/components/citizens_advice_components/section_links_spec.rb
This removes the following deprecations from component code:
- deprecated feedback_url from footer
- deprecated content slot from section links
- deprecated title attribute from callout
We deprecated all of this a while a go and to my knowledge our application code has since been updated so these should be safe enough to remove now.
> Remove deprecations

- CHANGELOG.md
- demo/app/views/layouts/application.html.erb
- demo/config/initializers/assets.rb
- demo/package-lock.json
- demo/package.json
- design-system-docs/frontend/styles/standalone.scss
- design-system-docs/frontend/styles/theme.scss
- design-system-docs/package-lock.json
- design-system-docs/src/_guides/using-with-rails.md
- scss/1-settings/_fonts.scss
- scss/1-settings/settings-imports.scss
- scss/3-generics/_fonts.scss
- scss/__tests__/__fixtures__/with-custom-font-path.scss
- scss/__tests__/__fixtures__/with-disabled-icon-font.scss
- scss/__tests__/generics.test.js
Our SCSS styles include `@font-face` declarations which are hard-coded with relative paths to the assets distributed as part of the node module.
Our main target environment is Rails. Historically we've targeted webpack environments via [shakapacker](https://github.com/shakacode/shakapacker) and used to rely on `resolve-url-loader` to resolve these font paths.
This is one way of loading assets in Rails but not the only way. For newer applications we favour using [cssbundling-rails](https://github.com/rails/cssbundling-rails) which ultimately delegates to the Rails asset pipeline using sprockets or propshaft.
Ultimately we want to provide a way of getting the font files into the right place so that applications can correctly resolve paths.
We can use the following config to tell Rails to …
> Improve font loading options

- contributing/testing-with-your-application.md
Adds a small guide to the contributing guides documenting how to configure your own Rails application to test local design system changes.
> Add a local testing guide

- design-system-docs/src/_component_docs/error-summary.md
Update the code snippet for including the JS code to support the ErrorSummary component.
I tried the original snippet, and it didn't work for me. The corrected version is [currently in use here](https://github.com/citizensadvice/public-website/blob/bdf5b4331382fb165d707f4e2e97c5c5f5eb64e0/app/javascript/packs/public-advice.js#L4), among other places.
> Fix JS documentation for `ErrorSummary` component

- design-system-docs/Gemfile
- design-system-docs/Gemfile.lock
- design-system-docs/plugins/builders/cads_builder.rb
ViewComponent 3.9+ introduced a change which depends on there being an active Rails request or controller in order to conditionally escape HTML. This causes an issue when run in bridgetown as there's no request and we're always rendering static html.
Whilst this is monkey patching an internal method this feels like the least worst approach as it removes just the single check that's dependent on the request whilst still keeping the underlying escaping.
(Temporarily) fixes #3145. Related issue: https://github.com/bridgetownrb/bridgetown-view-component/issues/8
> Patch bridgetown compatibility with view_component 3.9.0+

- .github/workflows/ci-workflow.yml
https://rubyonrails.org/2024/8/10/Rails-7-2-0-has-been-released
Updates our test matrix to include the new Rails 7.2 release and to account for the new Rails maintenance policy https://rubyonrails.org/maintenance
Explicitly test a "legacy" configuration using an older Ruby, Rails, and ViewComponent version to represent applications that have not been upgraded yet with the expectation that we'll drop Rails 6.1 along with ViewComponent 2.x when Rails 6.1 goes end-of-life on October 1st 2024.
> Add Rails 7.2 to test matrix

- CHANGELOG.md
- demo/spec/components/previews/header_preview.rb
- design-system-docs/src/_component_docs/header.md
- design-system-docs/src/_component_examples/_header/default.erb
- design-system-docs/src/_component_examples/_header/with_navigation.erb
- engine/app/components/citizens_advice_components/header.rb
- engine/spec/components/citizens_advice_components/header_spec.rb
This one came after an internal accessibility testing on the public site.
It was raised that:
> When scrolling the site with a screen reader (we did that with Jaws) the Cymraeg link at the top of the public website homepage is not specified as being in welsh language. As a result it is not read correctly.
I have checked with Voiceover screen reader on mac and even though the language is specified, it didn't change the pronunciation and unlike other languages, doesn't read numbers in the language specified. I would assume this is due to the Welsh language support on screenreaders - would be interesting to test with Jaws. I have still decided to raise a PR as I think it's a good practice to be able to pass the `lang` attribute.
> feat: allowing lang attribute to header links

- design-system-docs/Gemfile
- design-system-docs/Gemfile.lock
- design-system-docs/plugins/builders/cads_builder.rb
- design-system-docs/src/_components/foundations/borders_table.rb
- design-system-docs/src/_components/foundations/icon_grid.rb
- design-system-docs/src/_components/foundations/spacing_table.rb
- design-system-docs/src/_components/shared/app_breadcrumbs.rb
- design-system-docs/src/_components/shared/app_header.rb
- design-system-docs/src/_components/shared/arguments_table.rb
- design-system-docs/src/_components/shared/colour_table.rb
- design-system-docs/src/_components/shared/component_example.rb
- design-system-docs/src/_components/shared/component_example_source.rb
- design-system-docs/src/_components/shared/on_this_page.rb
Upgrades view_component in the docs website with an additional compatibility patch.
In version 3.15+ the docs build fails with the following error:
```sh
undefined method `controller' for an instance of Bridgetown::ERBView
```
This is similar to the error that was patched in #3362 but likely resurfacing because we applied the narrowest possible monkey patch originally.
Adjusts our patch for Bridgetown compatibility with view_component. Substituting in a controller covers what the library expects to be present.
Using `Bridgetown::ViewComponentHelpers` also conflicts with the presence of a `request` object. It turns out we don't need this for our use case so remove the include rather than attempting to patch around it.
> Docs website: Upgrade view_component with patch

- CHANGELOG.md
- engine/app/components/citizens_advice_components/footer.html.erb
- engine/app/components/citizens_advice_components/footer.rb
- engine/spec/components/citizens_advice_components/footer_spec.rb
Currently, if no feedback link title is specified and the feedback link is set to open in a new tab, the `aria-label` is " (opens in a new tab)".
This PR fixes this by using the default feedback link title as an `aria-label` fallback.
> fix: default aria-label for footer feedback link

- CHANGELOG.md
- package-lock.json
- package.json
Adds support for Rails 8 and removes support for EOL Rails 6.1.
There's an argument removing support for Rails 6.1 is a breaking change but we have no consumers using this version so recommending we do this as a minor version as there are otherwise no other changes.
> Prepare v6.3.0 release

- engine/Gemfile
- engine/Gemfile.lock
Workaround for
https://github.com/ruby-concurrency/concurrent-ruby/issues/1077 which is currently causing our Rails 7.0.x CI tests to fail.
This change shouldn't affect the published gem as this only controls what we install locally or in CI and consumers control their own application gem versions.
Can be removed when either a Rails 7.0.x patch is released or we remove support for Rails 7.0.x whichever is sooner (likely the latter as it is near EOL)
> Pin concurrent-ruby version for tests

- CHANGELOG.md
- scss/2-tools/_breakpoints.scss
- scss/2-tools/_typography.scss
- scss/7-utilities/_visibility.scss
This makes overriding the breakpoint settings possible in products that use the design system.  `@use` requires you to explicitly override variables when you import a module, rather than respecting what the global state of the `@use`d file is.  This changes ensures that the global values of the breakpoints are respected at all layers of the ITCSS triangle, allowing products to override the breakpoint variables as they wish.
The use case for this is a bit odd - in an energy app we are iframing a form into some advice content to provide a different type of journey for users.  The content columns width in an advice collection page is smaller than the medium breakpoint in the design system, so mobile styles were showing for the iframed app on desktop.
Similar to #3342
> feat: allow breakpoints to be overriden by products

- contributing/04-release-process.md
- demo/Gemfile.lock
- design-system-docs/Gemfile.lock
- design-system-docs/src/_guides/overview.md
- design-system-docs/src/_guides/using-with-rails.md
- engine/Gemfile.lock
- engine/lib/citizens_advice_components.rb
- engine/lib/citizens_advice_components/version.rb
- engine/spec/lib/citizens_advice_components/version_spec.rb
We currently fix the engine version to 0.1.0 which prevents us from using things like the deprecator to log version warnings and is at best just a little confusing.
Set the engine version to match the package version and add a spec to require them to match when updating the version.
> Set engine version

- engine/lib/citizens_advice_components.rb
- engine/lib/citizens_advice_components/engine.rb
Increase version to 8.0 now that we've released 7.0.0. Also remove a Rails version check as the minimum Rails versions supported is 7.1.0.
> Update deprecator horizon

- CHANGELOG.md
- design-system-docs/frontend/styles/_foundations.scss
- design-system-docs/src/_component_examples/_foundations/typography_link.erb
- design-system-docs/src/_component_examples/_foundations/typography_page_title.erb
- design-system-docs/src/_component_examples/_foundations/typography_small_paragraph.erb
- design-system-docs/src/_foundations/typography.md
- scss/4-elements/_typography.scss
The method we currently have for using typography classes requires you to either use a cads-prose container or a custom extend. This changes introduces some companion utility classes for applying paragraph and heading styles.
There's an ideal scenario where someone can use the design system without writing any custom CSS and whilst we don't want to provide endless utility classes working with paragraphs and headings is a common enough scenario that it helps to have matching classes to go with the lower level styles.
I've also restructured the typography guide for clarity, particularly to better cover the expected use of cads-prose as this is a frequent point of confusion as well as adding a section on the cads-page-title.
> Add new typography classes

- scss/6-components/_header.scss
It was originally missed in design that the button needed to be made smaller to fit in line with the search form in the heading, I've done some pairing with a designer to tweak this to get the alignment, shadow, etc, all agreed now.
> tweak header button sizing following design review

- CHANGELOG.md
- demo/cypress/e2e/skip-links.cy.js
- design-system-docs/src/_component_docs/header.md
- engine/app/components/citizens_advice_components/header.rb
- engine/config/locales/cy.yml
- engine/config/locales/en.yml
- engine/spec/components/citizens_advice_components/header_spec.rb
This is because the intent of skip links are to "skip blocks of content repeated between pages" and the navigation and footer are usually repeated between pages therefore it's unnecessary to include them in the skip links in order to satisfy that WCAG criteron. See https://webaim.org/techniques/skipnav/#multiple for more info.
> NAT-1249: change the default skip links to skip to only skip to the header component by default

- website/app/views/layouts/component_example.html.erb
Spotted one more small regression in the docs website, missing the no-js toggle code for component examples (especially when iframed)
> Add missing no-js toggle to component examples

- engine/app/components/citizens_advice_components/date_input.rb
- website/config/data/component_arguments.yml
Removes the dependency on the base Input component.
In it's previous form the field inherited from `Input` but needed to provide its own template and overrode almost all of the parent options. This makes sense as the date input isn't a single input, it's a group.
In practice the main way we use the date input is via `cads_date_field` which has a parallel implementation so keeping the two as legible as possible is important to avoid drift.
Our form components were written a long while before we introduced the form builder versions, now we have that we can stand to simplify the original interfaces a bit based on what we've learned.
> Simplify date input interface

- demo/spec/components/previews/textarea_preview.rb
- engine/app/components/citizens_advice_components/textarea.html.erb
- engine/app/components/citizens_advice_components/textarea.rb
- engine/spec/components/citizens_advice_components/textarea_spec.rb
Like with #3739 the textarea is another component where inheritance causes an issue. In this case the component both _inherits_ from `Input` but also _calls_ `Input` for it's template.
As a textarea ultimately doesn't behave the same way as an input (no type, value handled differently, can have rows etc.) it's simpler for us to inline the parts we need again.
It's possible we might be able to extract a `FormField` component which handles just some shared markup, but cautious about introducing _new_ interfaces here. Particularly as in reality the main way we use form fields now is through the new form builder.
> Simplify textarea interface

- CHANGELOG.md
- scss/7-utilities/_visibility.scss
- scss/__tests__/__snapshots__/utilities.test.js.snap
Has an old deprecation comment and a search confirms that we've never used this in any internal or product code.
> Remove cads-sr-only-focusable class

- demo/spec/components/previews/select_preview.rb
- engine/.rubocop.yml
- engine/app/components/citizens_advice_components/select.html.erb
- engine/app/components/citizens_advice_components/select.rb
Another component where inheritance complicates the interface.
Like with a textarea a select has subtle differences from an input (no type, value handled differently).
Includes a public `render_select_options` method to make it easier for consumers to sub-in things like `grouped_options_for_select`. We could probably support that as a first-class feature but would need more updates to the form builder for that to work properly so just introducing a seam to do it for now.
> Simplify select interface

- CHANGELOG.md
- demo/spec/components/previews/select_preview.rb
- demo/spec/components/previews/textarea_preview.rb
- engine/.rubocop.yml
- engine/app/components/citizens_advice_components/select.html.erb
- engine/app/components/citizens_advice_components/select.rb
- engine/app/components/citizens_advice_components/textarea.html.erb
- engine/app/components/citizens_advice_components/textarea.rb
- engine/spec/components/citizens_advice_components/select_spec.rb
- engine/spec/components/citizens_advice_components/textarea_spec.rb
A re-do of #3740 and #3741 to simplify the Textarea and Select component interfaces respectively with the key difference of logging a deprecation warning for the inherited `type` attribute rather than straight removing it to give time for consuming applications to update their code first.
> Deprecate type option on Textarea and Select components
