scss/base/1-settings/_typography.scss, scss/base/4-elements/_links.scss, scss/base/4-elements/_typography.scss, styleguide/tokens/typography.md
- Remove semi-bold and extra-bold font weight
- Add H4 and small body text 
- Update type sizes and remove blue for heading 
- Add link interactive states
Details in this issue: https://github.com/citizensadvice/design-system-testing/issues/1
=> Typography updates

scss/base/1-settings/_colour-language.scss, scss/base/1-settings/_colour-palette.scss, scss/base/2-tools/_borders.scss, scss/base/6-components/_navigation.scss, scss/base/6-components/_search.scss, styleguide/styles.scss
Remove colours that are not used and add updated colours
Based on design work by Shakira and Sonia
These changes will need to be reviewed by the design system working group and are subject to change. But at least we are now using colour language throughout.
=> Update colour language and palette

scss/6-components/_breadcrumbs.scss, styleguide/components/breadcrumbs.js
Update breadcrumbs to truncate long labels (note: consumer need to use the title tag to set the label accessibly).
=> Breadcrumb styles

scss/4-elements/_links.scss
Using the correct focus colours and colour language
=> Update link styles

CHANGELOG.md, scss/4-elements/_forms.scss
Centre the small radio checkmark correctly.
=> NP-206 Radio button styles bug-fix

.storybook/webpack.config.js, package-lock.json, package.json
This should fix all the npm audit vulnerabilities.
=> Updating highlight-loader package and webpack config

haml/_input.html.haml, haml/_radio_group.html.haml, haml/_radio_group_small.html.haml, scss/1-settings/_colour-language.scss, scss/2-tools/_interactive-elements.scss, scss/4-elements/_buttons.scss, scss/4-elements/_forms.scss, scss/6-components/_breadcrumbs.scss, scss/6-components/_header.scss, scss/6-components/_navigation.scss, scss/6-components/_search.scss, styleguide/haml_locals.rb
See ticket for updates included https://citizensadvice.atlassian.net/secure/RapidBoard.jspa?rapidView=159&modal=detail&selectedIssue=NP-243
=> NP-243 design updates

CHANGELOG.md, haml/_footer.html.haml, haml/_website_feedback.html.haml, scss/6-components/_footer.scss, scss/6-components/_website-feedback.scss, scss/6-components/components-imports.scss, styleguide/component.stories.js
Website feedback component added. Note that this is used in the footer so the footer tests will have to be rerun @celonicolosi
=> NP-237 Website feedback

scripts/vr-test.js
This fixes a crash on @celonicolosi's machine.
=> fix: increase storybook log buffer to 5mb

CHANGELOG.md, haml/_notice_banner.html.haml, scss/6-components/_notice-banner.scss, styleguide/haml_locals.rb
Updates the notice banner to use the new content model structure.
=> NP-270 Dynamic notice banner label

Jenkinsfile, docker-compose.yml
**this is an experimental branch - please wait to review it - comments welcome but don't be sad if everything changes **
- set some env variables
- set the build name
- combine lint and test stages
- run docker-compose in a sandbox (https://github.com/citizensadvice/jenkins-global-pipeline-lib/blob/master/vars/withDockerSandbox.groovy)
- remove 'manual' cleanup
- run a groovy formatter over the file
=> NP-336: build: jenkinsfile tweakage

CHANGELOG.md, package-lock.json, package.json, scss/6-components/_navigation.scss, styleguide/component.stories.js, testing/package-lock.json, testing/package.json
[citizensadvice/priority-navigation](https://github.com/citizensadvice/priority-navigation) is set up and I've published the package. This change makes now uses that package.
I've also run `npm audit fix`.
=> NP-350 - chore: update priority-nav to use citizens advice owned package.

Jenkinsfile, bin/jenkins/fix_visual_test_report
This re-uses the `withSlackNotifier` function which requires an exception to trigger a failure condition.
I'm considering creating a fresh function that can take a boolean instead but let's see if this works first.
=> NP-303 - Report build failure and success to slack

Jenkinsfile
Only show succcess or failure messages in slack for non-pr branches.
=> feat: only report build status for deploy branches [NP-367]

CHANGELOG.md, scss/4-elements/_lists.scss
Fix missing padding in numbered lists.
=> NP-453 Numbered lists spacing

CHANGELOG.md, haml/_header.html.haml, styleguide/haml_locals.rb
The text for the sign in/out link is now configurable.
=> NP-478 sign-in/out

CHANGELOG.md, scss/6-components/_callout.scss, styleguide/haml_locals.rb, styleguide/samples/_advice_collection.html.haml, styleguide/samples/_advice_collection_adviser.html.haml
The callout Urgent type is now Important.
=> feature: Change callout type name [NP-523]

CHANGELOG.md, haml/_navigation.html.haml, styleguide/haml_locals.rb
Gets the nav links dynamically as an array. No changes to styles or output so VRTs are the same.
=> NP-557 dynamic nav links

CHANGELOG.md, haml/_contact_details.html.haml, scss/6-components/_contact_details.scss, styleguide/haml_locals.rb
Remove title from contact details, that is now coming in the body so style accordingly the first p tag.
=> feature: Contact details structure [NP-525]

package-lock.json
https://npmjs.com/advisories/1523
=> fix: 798 lodash security issues

CHANGELOG.md, scss/1-settings/_fonts.scss
Immediately show fonts and swap font when it loads.
=> bug: font loading fix [NP-581]

.storybook/preview-head.html, CHANGELOG.md, docs/iframe.html, scss/4-elements/_forms.scss, scss/6-components/_callout.scss, scss/6-components/_search.scss, styleguide/styles.scss, styleguide/tokens/languages.md
https://citizensadvice.atlassian.net/browse/NP-643
=> feat: remote support for Scottish Gaelic [NP-643]

testing/features/buttons.feature, testing/features/step_definitions/buttons_steps.rb, testing/features/support/core_ext/capybara/node/element.rb, testing/features/support/pages/buttons.rb, testing/features/support/parameter_types.rb
Add Buttons specification for Design System
In line with CR from other PR, have removed the testing for changing colours to be just detecting a change, and not specifically what change as this is handled by visual regression.
=> featurer: Specification for Buttons [NP-624]

Jenkinsfile, bin/docker/a11y-test, docker-compose.yml, scripts/update-pa11y-config.js, scripts/wcag-test.js, testing/Dockerfile.wcag, testing/wcag/.pa11yci.ci.json, testing/wcag/.pa11yci.local.json
* Add Docker config for wcag-tests
** installing puppeteer in alpine is not straightforward so use a pre-build image and add pa11y
* Update pa11y scripts to generate docker compatible config
* Add pa11y-test to Jenkinsfile.
=> feat: run pa11y Accessibility tests during Jenkins build [NP-741]

Jenkinsfile
Add in a bunch of new test candidate drivers for branch testing. Also added to public-website
=> feature: Add extra tests for Browserstack [NP-731]

.nvmrc, CHANGELOG.md, CONTRIBUTING.md, Dockerfile, scripts/build.js
As public-website is being built with v14 I updated this to be v14 too. v12 will become maintnance only next month.
=> chore: Update node to v14

CHANGELOG.md
Add changes to changelog that I should have done in #293 (😬 )
=> docs(changelog): update changelog for breadcrumb and search work in #293

testing/features/support/drivers/browserstack/base.rb
Reverts citizensadvice/design-system#316
=> Revert "feature: TEMPORARY - New browserstack endpoint [NP-1048]"

testing/features/error_summary.feature
Tag error summary with @future-release. Fixes build.
=> Tag error summary with @future-release

testing/features/buttons.feature, testing/features/step_definitions/buttons_steps.rb, testing/features/support/components/all.rb, testing/features/support/components/button/primary.rb, testing/features/support/components/button/secondary.rb, testing/features/support/components/button/tertiary.rb, testing/features/support/components/buttons.rb
Same as the other port over tests. We've migrated the existing tests over from the old legacy code to the new "state-d" format.
Only thing worth noting here is because these are primitive tests, I've tried to "zazz" them up a little, without straying over into the VRT territory
=> feature: Port over Buttons tests [NP-1059]

testing/features/footer.feature, testing/features/step_definitions/footer_steps.rb, testing/features/support/components/footer.rb, testing/features/support/helpers/page.rb
Add new feature to test the footer component. Because the footer component has a link that users can leave feedback on the pages that they are on, it also adds a new helper to handle newly opened tabs.
=>  feature: DS - Automated Tests - Footer [NP-733]

testing/features/footer.feature, testing/features/header.feature, testing/features/step_definitions/footer_steps.rb, testing/features/step_definitions/header_steps.rb
Fix step clash caused by 2 similar specs being added simultaneously
=> Hotfix: Automation Step Issue

Jenkinsfile, docker-compose.yml
Mostly the same as https://github.com/citizensadvice/design-system/pull/373, but rebased to master and adding the code to stop the build after collecting the docker-compose logs.
=> feature: Enable cache-from feature to speed up builds (NP-1159)

haml/_input.html.haml, haml/_textarea.html.haml
Remove `cads-input-group`. It doesn't exist.
=> Remove cads-input-group

README.md, package-lock.json, styleguide/documentation/getting-started.stories.mdx, styleguide/translations/translated.stories.mdx
For our own benefit, but also for @tonyto. Creates a dedicated "Using with Rails" guide to replace the current getting started docs. Covers all the config you currently need to get things running with a Rails app.
=> Using with Rails guide

testing/features/support/hooks.rb
Missed from previous PR review
=> Fix up blockVar name

CHANGELOG.md, package-lock.json, package.json, stats/size.json
**Bugfixes**:
* Search: Normalise search button styles and use 44px height. Removed `cads-button` from search input.
* Pagination: Update pagiantion designs and add reference aria examples.
* Forms: Add `name` attribute to input haml partial
**New features**:
* ⬆️ Footer: Supply feedback link and links using template locals (NP-662)
=> v2.1.0 alpha.1

scss/1-settings/_colour-language.scss, scss/6-components/_search.scss
One more change to allow the search button to be styled.
=> feature: allow search button to be styled

CHANGELOG.md, haml/_footer.html.haml, haml/_header.html.haml, haml/_navigation.html.haml, locales/cy.yml, locales/en.yml, scss/6-components/_skip-links.scss, scss/6-components/components-imports.scss, styleguide/components/header/header.stories.mdx, styleguide/sample-pages/advice-collection/_advice_collection.html.haml, styleguide/sample-pages/advice-collection/_advice_collection_adviser.html.haml, testing/wcag/pa11yci.ci.js, testing/wcag/pa11yci.local.js
Adds three skip links to the header that become visible when they receive focus.
- added markup and styles to present links
- added welsh translations from current site
- updated header documentation
- updated samples pages
- updated changelog
=> feature: add skip links [NP-1181]

CHANGELOG.md, package-lock.json, package.json, stats/size.json
- 2.1.0-alpha.3
- Update CHANGELOG
=> release/v2.1.0 alpha.3

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> Release/v3.0.0 alpha.0

package.json
Noticed that the repository URL was pointing to an old testing repo so correcting that.
=> Point repository URL to the correct location

.editorconfig, .gitignore, .prettierignore, Jenkinsfile, Rakefile, docker-compose.yml, docker/Dockerfile.ruby_host, testing/cucumber.yml, testing/features/support/automation_logger.rb, testing/features/support/driver.rb, testing/features/support/helpers/page.rb
Adding extra grid tests that would work in an acceptably fast fashion meant that we needed parallelisation in this Jenkinsfile. Zhelyan did a basic rewrite converting everything to scripted pipeline so we weren't mixing the two styles anymore.
That left in a lot of bugs and weirdnesses that had accumulated and emphasised a couple of others. This PR takes that code, makes it fit the NP coding style a bit closer, and fixes some of the bugs
- set the tab width to 2 spaces for consistency with other files
- added a try finally block to replicate the post always section of the declarative pipeline
- restructured the artifacts folder structure so information about what tests were run is encoded
=> refactor: Convert to scripted pipeline [NP-1174]

Jenkinsfile
Fixes a naming issue on the master branch, which wasn't visible until the code got merged to the master branch.
=> Fixed docker image naming issue on master

CHANGELOG.md, package-lock.json, package.json, stats/size.json
- Footer: links accept icon option, which is displayed after then link label
=> Release/v3.1.0 alpha.0

testing/features/header.feature, testing/features/step_definitions/header_steps.rb, testing/features/support/components/header/standard.rb, testing/features/support/drivers/browserstack/base.rb, testing/features/support/helpers/env_variables.rb, testing/features/support/hooks.rb
Make sure to account for mobile header differences!
=> bugfix: Make mobile work on header tests [NP-761]

Jenkinsfile
Docker is now rate limiting anonymous image pulls by IP address. This adds authentication so that all our pulls inside this build job are associated with our account.
=> bugfix: Wrapped pipelines with docker hub credentials [NP-1344]

CHANGELOG.md, package-lock.json, package.json, stats/size.json
This one's so Kath can finish off a PW ticket related to adding country prefixes to links.
=> Release/v3.2.0 alpha.0

package-lock.json, package.json
Merges together a handful of related dependabot updates.
=> Upgrade babel dependencies

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> Release/v4.0.0 alpha.0

CHANGELOG.md, scss/3-generics/_fonts.scss, scss/4-elements/_links.scss, scss/5-objects/_prose.scss, styleguide/foundations/typography/typography.stories.mdx
=> feature: external links [NP-1382]

CHANGELOG.md, package-lock.json, package.json, stats/size.json
**New**
- 🔗 Links: added external link styling. Links within cads-prose are styled automatically [NP-1382]
- 🌎 Navigation: Header links are now added to the 'More' dropdown and no-js support (NP-1235)
[NP-1382]: https://citizensadvice.atlassian.net/browse/NP-1382
=> release/v4.0.0 alpha.1

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> release/v4.0.0 alpha.3

testing/features/header.feature
Only test header format on desktop resolutions
NB: Physical Testing will be done manually for now. Once the alpha is cut
=> bugfix/refactor: Header layout [NP-1235]

CHANGELOG.md, package-lock.json, package.json, stats/size.json
**New:**
- 🎯 Targeted content: New adviser specific variant
- 🗣️ Callouts: Support callouts within callouts
**Bugfixes:**
- ⬜ Tables: Give tables an explicit white background to allow them to be used against darker backgrounds
=> Release/v4.0.0 alpha.4

haml/_footer.html.haml, testing/features/asset_hyperlink.feature, testing/features/buttons.feature, testing/features/callout.feature, testing/features/contact_details.feature, testing/features/error_summary.feature, testing/features/footer.feature, testing/features/header.feature, testing/features/input.feature, testing/features/page_review.feature, testing/features/search.feature, testing/features/step_definitions/asset_hyperlink_steps.rb, testing/features/step_definitions/buttons_steps.rb, testing/features/step_definitions/common_steps.rb, testing/features/step_definitions/contact_details_steps.rb, testing/features/step_definitions/error_summary_steps.rb, testing/features/step_definitions/footer_steps.rb, testing/features/step_definitions/header_steps.rb, testing/features/step_definitions/input_steps.rb, testing/features/step_definitions/language_steps.rb, testing/features/step_definitions/page_review_steps.rb, testing/features/step_definitions/search_steps.rb, testing/features/support/components/footer/minimal.rb, testing/features/support/components/header/standard.rb, testing/features/support/components/page_review/standard.rb, testing/features/support/helpers/page.rb, testing/features/support/helpers/regex.rb
I have gone through the entire automated tests repo. I have added tests for each component that is language specific, amended existing ones, and flagged ones not fully working.
=> feature: Automation - Review language specific tests [NP-1328]

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> Release/v4.0.0 alpha.5

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> Release/v4.0.1 alpha.0

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> Release/v4.0.2 alpha.2

scss/4-elements/_links.scss
Makes the nice pointer appear when hovering over a button-link link-button.  Yuge!
=> feat: pointer on linkbutton hover NP-1708

Jenkinsfile
Copy of PR#900 in public-website. Use the dynamic service accounts in design-system also.
=> Use browserstack service accounts

Jenkinsfile
Find out / fix browserstack dynamic allocation issue
=> bugfix: Browserstack Allocation Issue [NP-1752]

Gemfile, Gemfile.lock
MInor gem bump to keep both repos in sync fixing a weird i18n bug
=> bugfix: i18n weirdness [NP-1759]

haml/_header.html.haml, testing/features/callout.feature, testing/features/contact_details.feature, testing/features/footer.feature, testing/features/header.feature, testing/features/page_review.feature, testing/features/search.feature, testing/features/support/components/header/standard.rb, testing/features/support/components/page_review/standard.rb, testing/features/support/components/search/standard.rb, testing/features/targeted_content.feature
- all scenarios reviewed
- all falling / future releases / NP-xxxx tags removed
- some scenarios fixed
- one scenario removed (Scenario: Content is not auto-opened if previously interacted with)
=> Feature/NP-1601 Review v4 build of DS

testing/features/support/drivers/browserstack/ios.rb
Have better granularisation of new features (Possibly aid in runtime speed / flakiness)
=> Bump appium versions

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> Release/v4.0.4 alpha.0

scss/1-settings/_colour-language.scss, scss/2-tools/_interactive-elements.scss, scss/6-components/_navigation_greedy-nav.scss
Add pointer to hover on nav more button
Decouple nav border hover colour from link text hover colour
=> feat: add pointer to dropdown toggle, decouple border color

locales/cy.yml
=> chore: add translation

testing/features/header.feature, testing/features/navigation.feature
After the recent bugfixes and release we can now
- Remove all future release tags (Again for now)
- Remove one failing test which is now fixed
=> re enable (a few), tests [NP-1884]

testing/.env.example, testing/browserstack_ci.env, testing/features/support/automation_logger.rb, testing/features/support/driver.rb, testing/features/support/env.rb, testing/features/support/helpers/env_variables.rb, testing/grid_ci.env
Same as sister PR.
- Refactor logger creation
- Allow passing log info to stdout
- Standardise log levels
=> feature: Add new log enhancements (Copy from PW) [NP-1802]

CHANGELOG.md, package-lock.json, package.json, stats/size.json
**New**
- 🔗 Links: Links and Link Buttons no longer have default browser outlines
- 🌠 Logo: Add a transparent bottom border to the logo link
**Bugfixes**
- 🧭 GreedyNav: Fix greedy nav behaviour when resizing
=> Release/v4.0.5 alpha.0

package-lock.json, package.json
+ typescript@4.2.4
+ cssnano@4.1.11
=> chore: npm dep updates 2021-04-08

testing/features/pagination.feature, testing/features/step_definitions/pagination.rb, testing/features/support/components/pagination/example.rb, testing/features/support/components/pagination/paging_info.rb
A couple of scenarios for automate the Pagination component.
=> feature: DS Automation Pagination [NP-1882]

testing/features/notice_banner.feature, testing/features/step_definitions/notice_banner.rb, testing/features/support/components/notice_banner.rb, testing/features/support/components/notice_banner/notice_banner.rb
Simple automation for Notice Banner in Design System.
=> feature: DS Automation - Notice Banner [NP-1881]

CHANGELOG.md, package-lock.json, package.json, stats/size.json
=> Release/v4.0.6 alpha.0

testing/features/support/drivers/browserstack/base.rb
Ronseal PR. Same as PW mirror PR.
=> Enable network logs same as PW

CHANGELOG.md, package-lock.json, package.json
=> Release/v4.1.0 alpha.0

package-lock.json, package.json
=> 4.1.0-alpha.1

.github/dependabot.yml
So close and yet so far…one more try.
=> Correct case for dependency-name include

testing/features/components/navigation.feature, testing/features/support/cucumber_info/skipper.rb, testing/features/support/helpers/env_variables.rb
JIRA ticket ongoing to investigate further
=> hotfix: Don't run problematic nav test against Apple things

CHANGELOG.md, package-lock.json, package.json
=> release/v4.1.1 alpha.0

testing/features/components/buttons.feature, testing/features/components/step_definitions/buttons_steps.rb, testing/features/support/components/buttons/link_button.rb
Added simple spec to validate link button w3c props
=> feature: Button Audit [NP-2113]

testing/features/components/breadcrumbs.feature, testing/features/components/step_definitions/breadcrumbs_steps.rb, testing/features/support/components/breadcrumbs/sitewide.rb
It appears that some of these are identically styled and functional (So I just removed duplicate tests and placed notes)
If I'm wrong and they are distinct components I'll re-add the tests in.
=> feature: Breadcrumbs Test Audit [NP-2112]

package-lock.json, package.json
=> chore: update, audit

.github/workflows/ci-workflow.yml
Mirrors the previous cron build we had in the Jenkinsfile. On @luke-hill's request.
=> Run actions workflow on a schedule

CHANGELOG.md, package-lock.json, package.json
=> Release/v4.2.0 alpha.0

.storybook/preview.js, styleguide/documentation/roadmap.stories.mdx
Adds a small roadmap for future versions of the design system into storybewk.
=> docs: initial roadmap

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/new-feature.md
A couple of suggested issue templates so I can demo them in the next design system working group.
Not worried too much about the text right now - just want to show the feature to the group.
=> Issue templates

CHANGELOG.md, package-lock.json, package.json
=> Release/v4.3.0 alpha.0

.github/ISSUE_TEMPLATE/enhancement.md
Adds an enhancement issue type template
=> feat: add enhancement issue template

CHANGELOG.md, package-lock.json, package.json
=> Release/v5.0.0 alpha.0

CHANGELOG.md, package-lock.json, package.json
=> Release/v5.1.0 alpha.0

contributing/release-process.md
Small docs update for people running on a brand new machine for publishers (`npm login`)
=> docs: npm login details

.github/CODEOWNERS
Anointing @marianayovcheva with a codeowner 👑
=> feat: make MY a codeowner

CHANGELOG.md, package-lock.json, package.json
=> Release/v5.2.0 alpha.3

design-system-docs/src/_layouts/component.erb, design-system-docs/src/_layouts/default.erb, design-system-docs/src/index.md
Adds temporary homepage layout.
=> feat: add layout to homepage

.github/dependabot.yml
=> Ignore storybook dependencies from dependabot

.github/dependabot.yml, engine/Gemfile, engine/Gemfile.lock, engine/citizens_advice_components.gemspec, engine/spec/components/citizens_advice_components/footer_spec.rb
- Upgrade citizens-advice-style-ruby in engine to v7
- Fix warnings from version upgrade
- Add engine to dependabot rules
=> Upgrade citizens-advice-style-ruby in engine

demo/Gemfile, demo/Gemfile.lock
https://github.com/github/view_component/issues/1315
=> Pin view_component to 2.50.0

bin/setup
With the recent experience with external contributions and with the addition of consistent dev scripts in https://github.com/citizensadvice/design-system/pull/1906 I thought I'd try a fresh clone of the project to check for any other pain points.
Adds a couple of extra steps to the top-level setup script:
1. Runs a build after the initial install step
2. Adds the docs set up script to the top-level one
This should mean that you can run `bin/setup` at the top-level followed by `bin/dev` within either the demo app directory or docs site directory to get a working install.
=> Updates after running a fresh setup

design-system-docs/src/_foundations/animations.md
Copying content from Storybook into Bridgetown
=> feat: adding animations page

.github/dependabot.yml
- Removes old top-level bundler rule
- Removes old testing rule
- Adds missing npm rule to demo app
- Adds rules fro design system docs site
=> Update dependabot rules

CHANGELOG.md, package-lock.json, package.json
Making a release for the `legend_heading` update to form groups
=> v5.3.0-alpha.1

CHANGELOG.md, engine/config/locales/cy.yml, engine/config/locales/en.yml, src/ts/targeted-content/__snapshots__/targeted-content.test.ts.snap, src/ts/targeted-content/targeted-content.test.ts, src/ts/targeted-content/targeted-content.ts, styleguide/examples/sample_pages/content-sample.html, styleguide/examples/targeted_content/adviser.html, styleguide/examples/targeted_content/anchor.html, styleguide/examples/targeted_content/default.html
https://citizensadvice.atlassian.net/browse/NP-2771
Changed the `aria-label` of the close button from `hide` to `close` as suggested by DAC
=> DAC - Label in name (A)

CHANGELOG.md, engine/app/components/citizens_advice_components/input.html.haml, engine/app/components/citizens_advice_components/input.rb, engine/spec/components/citizens_advice_components/input_spec.rb, styleguide/examples/input/additional_attributes.html, styleguide/examples/input/hint.html, styleguide/examples/input/type.html, styleguide/examples/sample_pages/form-sample.html, styleguide/examples/text_input/additional_attributes.html, styleguide/examples/text_input/fixed_widths.html, styleguide/examples/text_input/hint.html, styleguide/examples/text_input/type.html, styleguide/examples/textarea/additional_attributes.html, styleguide/examples/textarea/hint.html
This is a recommendation coming from the referrals accessibility report. 
https://citizensadvice.atlassian.net/browse/REF-427
=> Ref 427 dac hint usability 01

CHANGELOG.md, package-lock.json, package.json
=> v5.4.0-alpha.0

design-system-docs/src/_component_docs/contact-details.md, design-system-docs/src/_component_examples/_contact_details/_defaults.yml, design-system-docs/src/_component_examples/_contact_details/example.erb
Adding the contact details component to the new docs site
=> feat: contact details component added to the new site docs

design-system-docs/src/_component_docs/callout.md, design-system-docs/src/_component_examples/_callout/_defaults.yml, design-system-docs/src/_component_examples/_callout/adviser.erb, design-system-docs/src/_component_examples/_callout/example.erb, design-system-docs/src/_component_examples/_callout/important.erb, design-system-docs/src/_component_examples/_callout/nested.erb, design-system-docs/src/_component_examples/_callout/standard.erb, design-system-docs/src/_component_examples/_callout/variable_heading_levels.erb, design-system-docs/src/_data/component_arguments.yml, engine/app/components/citizens_advice_components/callout.html.erb, engine/app/components/citizens_advice_components/callout.html.haml
Added the callout component to the new docs site. I had to convert the haml file to erb
=> feat: adding callout component to the new docs site

CHANGELOG.md, package-lock.json, package.json
Pre-release for v5.4.1-alpha.0
=> v5.4.1-alpha.0

design-system-docs/frontend/styles/_sample-styles.scss, design-system-docs/frontend/styles/theme.scss, design-system-docs/src/_component_docs/section-links.md, design-system-docs/src/_component_examples/_section_links/_defaults.yml, design-system-docs/src/_component_examples/_section_links/default.erb, design-system-docs/src/_component_examples/_section_links/with_additional_attributes.erb, design-system-docs/src/_component_examples/_section_links/with_custom_content.erb, design-system-docs/src/_data/component_arguments.yml
Migrate section links component docs. Depends on https://github.com/citizensadvice/design-system/pull/2321
=> Migrate section links component docs

engine/app/components/citizens_advice_components/pagination.html.erb, engine/app/components/citizens_advice_components/pagination.html.haml, styleguide/examples/pagination/with_fifth_page.html, styleguide/examples/pagination/with_first_page.html, styleguide/examples/pagination/with_last_page.html, styleguide/examples/pagination/with_second_page.html, styleguide/examples/pagination/with_tenth_page.html
=> Convert pagination to ERB

engine/app/components/citizens_advice_components/navigation.html.erb, engine/app/components/citizens_advice_components/navigation.html.haml, styleguide/examples/header/with_navigation.html, styleguide/examples/navigation/example.html, styleguide/examples/sample_pages/content-sample.html
=> Convert navigation to ERB

CHANGELOG.md, package-lock.json, package.json
=> v5.5.0-alpha.1

CHANGELOG.md, package-lock.json, package.json
=> v5.5.0-alpha.2

CHANGELOG.md
Updating the changelog in preparation to run an alpha release
=> feat: updating changelog

demo/package.json, demo/yarn.lock
=> chore: js deps /demo

CHANGELOG.md, package-lock.json, package.json
=> v5.5.0-alpha.3

demo/Gemfile, demo/Gemfile.lock, demo/config/environments/production.rb, demo/lib/tasks/generate_examples.rake, engine/Gemfile, engine/Gemfile.lock, engine/app/components/citizens_advice_components/pagination.rb, engine/spec/components/citizens_advice_components/badge_spec.rb, engine/spec/components/citizens_advice_components/breadcrumbs_spec.rb, engine/spec/components/citizens_advice_components/callout_spec.rb, engine/spec/components/citizens_advice_components/checkbox_group_spec.rb, engine/spec/components/citizens_advice_components/checkbox_single_spec.rb, engine/spec/components/citizens_advice_components/contact_details_spec.rb, engine/spec/components/citizens_advice_components/disclosure_spec.rb, engine/spec/components/citizens_advice_components/footer_spec.rb, engine/spec/components/citizens_advice_components/input_spec.rb, engine/spec/components/citizens_advice_components/navigation_spec.rb, engine/spec/components/citizens_advice_components/notice_banner_spec.rb, engine/spec/components/citizens_advice_components/on_this_page_spec.rb, engine/spec/components/citizens_advice_components/page_review_spec.rb, engine/spec/components/citizens_advice_components/pagination_spec.rb, engine/spec/components/citizens_advice_components/radio_group_spec.rb, engine/spec/components/citizens_advice_components/search_spec.rb, engine/spec/components/citizens_advice_components/section_links_spec.rb, engine/spec/components/citizens_advice_components/success_message_spec.rb, engine/spec/components/citizens_advice_components/table_spec.rb, engine/spec/components/citizens_advice_components/targeted_content_spec.rb, engine/spec/components/citizens_advice_components/text_input_spec.rb, engine/spec/components/citizens_advice_components/textarea_spec.rb
Batched up a couple of dependabot updates to upgrade to the latest version of https://github.com/citizensadvice/citizens-advice-style-ruby
=> Upgrade citizens advice style

CHANGELOG.md, package-lock.json, package.json
Releasing a new alpha version of the design system to customise the footer legal summary (AdviserNet)
=> v5.5.0-alpha.4

demo/backstop-common.js, demo/cypress/e2e/targeted-content.cy.js, demo/cypress/support/commands.js, demo/visual-regression/engine_scripts/onReady.js, design-system-docs/config/webpack.defaults.js, package-lock.json, package.json, scripts/release.js, scripts/releaseHelpers.js, scss/1-settings/__tests__/settings.test.js, scss/2-tools/__tests__/grid.test.js, scss/2-tools/__tests__/typography.test.js, scss/3-generics/_fonts.scss, scss/7-utilities/__tests__/utilities.test.js, src/ts/disclosure/disclosure.ts, src/ts/greedy-nav/GreedyNav.test.ts, src/ts/greedy-nav/GreedyNav.ts, src/ts/header/header.ts, src/ts/on-this-page/on-this-page.ts, src/ts/targeted-content/targeted-content.ts, src/ts/utils/show-hide.test.ts, src/ts/utils/show-hide.ts
https://prettier.io/blog/2023/07/05/3.0.0.html
Major version for mostly internal structural reasons as far as I can tell. Actual changes to formatting seem minimal for us.
=> Upgrade to Prettier 3

CHANGELOG.md, package-lock.json, package.json
Alpha release including new ViewComponent 3 support.
=> v5.5.0-alpha.5

CHANGELOG.md, package-lock.json, package.json
Preparing a release containing the table upgrades.
=> v5.5.0-alpha.6

package-lock.json, package.json
Our typescript usage is minimal so a plain version bump appears to work.
Fixes #2950
=> Upgrade typescript versions

package-lock.json, package.json
The dependabot upgrade of glob [failed](https://github.com/citizensadvice/design-system/pull/3001) so I tried to manually upgrade locally and investigate - after manual upgrade there were no more issues
=> chore: upgrade glob to 10.3.10

website/content/components/button.md
Quick patch extracted from https://github.com/citizensadvice/design-system/pull/3793
=> Fix path to button image

demo/.gitignore, demo/package-lock.json, demo/package.json
The last remaining plugin was updated to support Cypress 15 so we can upgrade now.
=> Upgrade to Cypress 15
